### ISSUE TITLE
list of files that need some changes to the html in order to fit the gettext string annotation

### ISSUE THREAD

**Issue by ariandora** [cucumber-tony/cucumber-frontend#106]
Lets call this part 1
Files with plural forms to be fixed: 

client/components/audit/guests/_index.html
client/components/audit/sales/_index.html
client/components/audit/sessions/_index.html
client/components/audit/social/_index.html

Files with ternary to be fixed: e.g. {{ app.id ? "Edit" : "Create" }}

client/components/apps/_new.html
client/components/apps/_show.html
client/components/boxes/edit/_edit.html
client/components/boxes/show/_index.html
client/components/codes/_sessions.html
client/components/locations/boxes/_table.html
client/components/locations/boxes/dialog.html

Files with || to be fixed: e.g. {{box.description || 'Add a comment'}}

client/components/boxes/new/_add.html
client/components/boxes/show/_index.html
client/components/codes/_index.html
client/components/locations/clients/_index.html

**Comment by simonmorley** [comment]
I'll find one way to fix each one and send over to @ZakMooney for a full fix.

@ariandora The plural ones are tricky - what would you recommend to do about this??

**Comment by ariandora** [comment]
@simonmorley the only thing we need there is to make sure that the variables return 0 as well. Mostly the problem is {{ ::item._score || 0 }} --> the '|| 0'. Otherwise, there should be no problem with the plurals.

**Comment by simonmorley** [comment]
We should re-write this, since the action uses a word that should be translated.

https://github.com/cucumber-tony/cucumber-
frontend/blob/master/client/components/boxes/boxes.directives.js#L42-L69

**Comment by ariandora** [comment]
And part 2:

Files with plural forms to be fixed: 
client/components/locations/clients/codes.html
client/components/locations/index/_alerts.html
client/components/locations/index/_favourites.html
client/components/locations/index/_index.html

Files with ternary to be fixed: e.g. {{ app.id ? "Edit" : "Create" }}
client/components/charts/clients/_client_usage_chart.html
client/components/locations/clients/codes.html
client/components/locations/clients/_show.html
client/components/locations/index/_alerts.html
client/components/locations/index/map.html

Files with || to be fixed: e.g. {{box.description || 'Add a comment'}}
client/components/locations/clients/_index.html
client/components/locations/clients/_show_code.html

**Comment by ZakMooney** [comment]
Files with ternary to be fixed: e.g. {{ app.id ? "Edit" : "Create" }} & double tooltip

client/componentslocations/index/_index.html

**Comment by simonmorley** [comment]
Stuff For Simon To
--------------------------

client/components/codes/_sessions.html

**Comment by ariandora** [comment]
Part 3 

NOTE that some of these are in the title tag of anchors for example

Files with ternary to be fixed: e.g. {{ app.id ? "Edit" : "Create" }} 

client/components/locations/networks/_index.html
client/components/locations/networks/_show.html
client/components/locations/settings/_devices.html
client/components/locations/settings/_main.html
client/components/locations/settings/_notifications.html
client/components/locations/settings/_splash.html
client/components/locations/show/_warnings.html
client/components/locations/triggers/history/_index.html
client/components/locations/triggers/_show.html
client/components/locations/users/_index.html
client/components/reports/_pie_charts.html
