### ISSUE TITLE
Splash Design - Body font size not working

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#122]
![splashtypographysize](https://cloud.githubusercontent.com/assets/7580428/16446481/c059cdd6-3ddf-11e6-8015-d5ec8c7de660.gif)
The Body Size and Body Colour fields under Typography, in the splash design page, are linked together. Changing one changes the other.

**Comment by simonmorley** [comment]
@ZakMooney You can figure this one out next time ;)
