### ISSUE TITLE
BOX - Add to Zone not working from box settings page

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#148]
The warning appears to notify you that the box isn't in a zone. You click this to get taken to the zones page.

Can choose a zone but this doesn't update the device.

**Comment by ZakMooney** [comment]
Adding a box to a zone this way also seems to clear the added networks

**Comment by simonmorley** [comment]
This is was fixed in the backend - changes should be live this afternoon.
