### ISSUE TITLE
Navigation : Tables are not implemented uniformly on different pages

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#152]
This is hard to see if you have the original CT CSS. But is obvious is we use another style for the tables. The following sheet gives an overview.

![image](https://cloud.githubusercontent.com/assets/14114203/16586338/a6ae76bc-42c5-11e6-85d8-414764af8596.png)

**Comment by simonmorley** [comment]
Not 100% what you mean. Could you add a screenshot from the version you have so we can check. And also the corresponding vs in your own portal.

**Comment by Molkenbur** [comment]
Examples of all different implementation variants...

DEVICES (inside Frame, no Margin, Navigation):
![image](https://cloud.githubusercontent.com/assets/14114203/16610856/40ed9eb8-435e-11e6-96c3-b93ef6a73150.png)

CLIENTS (inside Frame, Margin, Navigation => good):
![image](https://cloud.githubusercontent.com/assets/14114203/16610891/7b969826-435e-11e6-9871-e9e7b4a31365.png)

ZONES (not inside Frame, no Margin, no Navigation)
![image](https://cloud.githubusercontent.com/assets/14114203/16610966/ed244d6c-435e-11e6-9b9c-d4d5001a5bdb.png)

TRIGGERS (inside Frame, Margin, no Navigation)
![image](https://cloud.githubusercontent.com/assets/14114203/16611003/26a70480-435f-11e6-9c74-65826a9c6bb9.png)

**Comment by ZakMooney** [comment]
Not 100% sure what you mean at the moment either.
Not sure what your desired end result with these tables are, and how they aren't meeting that.

Are you referring to the sorting arrow of the tables and the lines between columns?

**Comment by simonmorley** [comment]
Missing 'action' in header?

**Comment by Molkenbur** [comment]
The table views in my last comment are looking all slightly different. 
Is a navigation  (Page/Rows per page/first to last shown entry/total entries) mandatory or not?
Should the table be inside a white frame? 
Should there a gap between the table and the frame?

**Comment by simonmorley** [comment]
The zones table isn't in a card nor is the triggers. There's no reason to put them in one, it just increased the stuff on the page and reduces content size.

The boxes table _is_ in a card, because there is a chart at the top. The card separates them both.

No, at the moment, there is no requirement to add pagination to the tables since they don't support it. People don't generally add more than 25 zones or triggers but we will re-assess when they do / or have an issue ;)

Let me know if I have misunderstood again

**Comment by Molkenbur** [comment]
I understand.

But maybe you can eliminate the difference between DEVICES and CLIENTS.
Both have a card because of the chart, both have a pagination, but the DEVICES page has no gap between the table and the frame of the card. The CLIENTS page has this gap.

**Comment by simonmorley** [comment]
I see now:

<img width="169" alt="screen shot 2016-07-06 at 16 25 04" src="https://cloud.githubusercontent.com/assets/309336/16623539/48cbd798-4396-11e6-8fb9-2debad8e4e58.png">
<img width="157" alt="screen shot 2016-07-06 at 16 25 08" src="https://cloud.githubusercontent.com/assets/309336/16623540/48e5f86c-4396-11e6-865e-c85e0b86b2b4.png">

The border hits the card on one and not on the other. Nice spot.
