### ISSUE TITLE
No longer possible to add new locations

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#158]
its not possible to create any new locations for me right now. I deleted all locations and wanted to start from zero.

Actually the locations get counted up on https://alpha-preview.ctapp.io/#/
but on ctapp.io its still 0 locations.

dashboard:
![listed locations](https://cloud.githubusercontent.com/assets/19971953/16616326/c21ef914-437c-11e6-973c-0376f98477f3.PNG)
click on locations link:
![no locations found](https://cloud.githubusercontent.com/assets/19971953/16616331/c9fa9350-437c-11e6-9ab1-32ffcc9b7ce3.PNG)

ctapp.io:
![ctapp0](https://cloud.githubusercontent.com/assets/19971953/16616333/cd1f0638-437c-11e6-9c24-d69d0b2b8dba.PNG)

When creating a new location i can add devices but its not possible to return to this location later via dashboard and menu links. 

Either my account is broken or there is a general critical issue right now.
thanks in advance,
Christian

**Comment by AndrewMargarit** [comment]
@ChristianWinkler when you refer to ctapp.io are you pointing at the old dash?

**Comment by simonmorley** [comment]
I think the problem is that the locations aren't getting indexed / removed from the index after create and delete.

**Comment by ChristianWinkler** [comment]
i am pretty new to this project but i assume ctapp.io is the old dash

**Comment by simonmorley** [comment]
Yeah. You want to be in dashboard-preview.ctapp.io 

However, it's not portal related. It's the indexer in the backend. Will get sorted shortly ;)

**Comment by Illuminatt** [comment]
Works fine with the latest build. The issue can be closed for now.
