### ISSUE TITLE
Missing version information in CT cloud (enhancement)

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#159]
For testing reason it would be nice to have some version and commit information about the used frontend, backend and other relevant components summarized in the ct-cloud.
In general it should contain frontend: **versionnumber ( yyyy-mm-dd )** and the latest commit number.

**Comment by Molkenbur** [comment]
Proposal:

_Privacy Policy - Terms of Service
©2016 Cucumber Tony 
Version 2.0.0 (2016-06-07) b4c03f0_

The versionnumber is manually commited into the repo. The timestamp and build number are updated automatically by the build system. Variables might be a good way for the implementation.

**Comment by Molkenbur** [comment]
For me the commit number is optional.

**Comment by simonmorley** [comment]
Any thoughts on best way to get the commit version? I've looked at a few plugins but the docs are terrible. If someone wants to recommend something, I'll happily merge ;)

**Comment by simonmorley** [comment]
The commit hash isn't present in the beta or production branches. I think this is related to the fact we're building on circle and then deploying to heroku. It'll probably have to get inserted during the tests :|

**Comment by simonmorley** [comment]
Actually I am wrong, the commit is there. I've put under the copyright stuff for now. This needs formatting as per other issue.
