### ISSUE TITLE
Device - Zone Toast Lies

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#162]
The toast popup says not in a zone when the box is in a zone
![screenshot from 2016-07-06 18 09 46](https://cloud.githubusercontent.com/assets/7580428/16627638/0b5830ea-43a6-11e6-902a-375cc62cca9a.png)

**Comment by ChristianWinkler** [comment]
is this really fixed ? not sure but i think its still out there.... i expierenced it today

**Comment by simonmorley** [comment]
You will get this popup if the box isn't in a zone.

**Comment by ChristianWinkler** [comment]
I has a device added to a zone last week. Today i returned with Chrome V51 and Firefox (latest),
the device is online and a SSID is online but the popup showed up at least once in both browsers
![nozone_zone](https://cloud.githubusercontent.com/assets/19971953/16727123/cdbb4f66-475f-11e6-973e-4617746853bf.PNG)

**Comment by simonmorley** [comment]
What is the mac of the device?

**Comment by ChristianWinkler** [comment]
Posted mac in slackchat

**Comment by AndrewMargarit** [comment]
Did you get that on dashboard-preview ? the alpha-preview? Or your own branch?

**Comment by ChristianWinkler** [comment]
its not easy to retest it right now. "own frontend"is currenty offline and i am unable to open any device on dashboard-preview / alpha-preview right now.
As far i remember i noticed this issue on alpha-preview too, otherwise i would refrain from posting it here. I will check it again as soon as possible

**Comment by simonmorley** [comment]
Thanks. It should be ok. I think it happened right after the zone migration happened.
