### ISSUE TITLE
Location Settings : Location can not be deleted

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#166]
i have a location that can not be deleted anymore(archive/unarchive works, transfer works too).

![del_loc](https://cloud.githubusercontent.com/assets/19971953/16651849/f5fe20aa-4446-11e6-8a3a-8eca75082cd1.jpg)

there is a definition in the documentation that it should not be possible to delete locations with session data but i don't think this one is related.

**Comment by AndrewMargarit** [comment]
That looks about tight. You have data at that location.
The error message needs to be updated to reflect that better.

**Comment by simonmorley** [comment]
Thanks. We currently have some ! In the create and update actions to catch exceptions. 

This mean the errors are not displaying right now. We'll be removing soon.

**Comment by simonmorley** [comment]
This was a problem with the backend messages.

We've now updated these which fixes the problem.

Please note, the fixes were implemented in a branch that may take a few days to merge.
