### ISSUE TITLE
Devices : New device documentation

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#167]
![wi-fi management platform 4](https://cloud.githubusercontent.com/assets/2269441/16653203/54356bf6-4447-11e6-8504-8c7e7c263ecb.png)

The DOCUMENTATION Link points to
http://docs.cucumberwifi.io/category/72-getting-started

**Comment by simonmorley** [comment]
Closing this as Toni and Zak are going through the docs over the next week.
