### ISSUE TITLE
Everywhere : Spinner has scroll bars in Windowz and linux

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#17]
On a mac, things are groovy. On Ubuntu and Windowz, things are not so cool.

![spinner](https://cloud.githubusercontent.com/assets/309336/15869489/807ca7b2-2ce4-11e6-834d-fa15e2c99f58.png)

**Comment by danodemano** [comment]
Looks good mate!

![new](https://cloud.githubusercontent.com/assets/1128744/15987879/aaa417ba-3008-11e6-94e7-78b741d6a172.PNG)
