### ISSUE TITLE
Archived logo appearing at all locations

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#171]
When archiving one location and browsing to another the "archived" logo stays for all locations.
(Chrome V51 x64 / Windows 7)

**Comment by simonmorley** [comment]
Does it persist with a full page reload?

**Comment by ChristianWinkler** [comment]
no it can be removed with F5 or Ctrl+F5 until the user opens an archived location again.

**Comment by simonmorley** [comment]
Ok aces, the followed needs to be cleared on a routechange:

https://github.com/cucumber-tony/cucumber-frontend/blob/master/client/components/locations/locations.controller.js#L193-L195

**Comment by simonmorley** [comment]
I've fixed this (build waiting to deploy, please check circle).

There was also a visual issue where by the icon would not appear / disappear after archiving / unarchiving. The icon would only change after another link was clicked.

Should be good to go later today.
