### ISSUE TITLE
User Permissions - Things to Sort

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#185]
Please consolidate problems with the new permissions here.

So far:

- No menu link to users section
- Can't change a user's permission yet
- Can't add a user without adding to a location yet

**Comment by ZakMooney** [comment]
Number of locations under "Network Stats" incorrectly shows as 0 (doesn't count admin'ed locations)

**Comment by AndrewMargarit** [comment]
Permissions to confirm the AP manual reset request.

**Comment by simonmorley** [comment]
Missing locations from search.

**Comment by simonmorley** [comment]
I've sorted the number of locations now in the backend.

**Comment by simonmorley** [comment]
@ZakMooney I can confirm the popup *does* appear when a box is reset. The window displays at the bottom

@AndrewMargarit The reset would not work in the old dashboard, since resets have been migrated to the new version

**Comment by simonmorley** [comment]
The only thing I need to do is add a menu link for the users.. The addition of users via the API directly will come later - probably August Milestone

**Comment by simonmorley** [comment]
Menu link added, will be on beta later
