### ISSUE TITLE
Disconnect Client Not Working

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#199]
The disconnect client button doesn't work. Mainly because we haven't actually hooked this up yet in openwrt. 

Disconnect from splash should work. 

We should probably remove this from the menu while we test.

**Comment by simonmorley** [comment]
Note for @AndrewMargarit

**Comment by AndrewMargarit** [comment]
With me

**Comment by simonmorley** [comment]
@AndrewMargarit Can we get the disconnect code sorted for the boxes so we can run a payload and disconnect.

I believe the intention was to disconnect and add to the blacklist since the client will reconnected immediately.

**Comment by AndrewMargarit** [comment]
Yes, that's the one.
We can do it in this sprint

**Comment by simonmorley** [comment]
Temp. removed the link from the index

**Comment by simonmorley** [comment]
@AndrewMargarit @ZakMooney Can one of you test the logout button works - I removed the disconnect button - I'm talking about the splash logout button.

**Comment by ZakMooney** [comment]
@simonmorley Logout worked fine in my tests

**Comment by simonmorley** [comment]
Now implemented in SocketMan
