### ISSUE TITLE
Devices - Zone Visual

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#203]
![visual - devices zone](https://cloud.githubusercontent.com/assets/2269441/16912530/9332bc94-4cdc-11e6-96d1-6f52cb35e617.gif)

The AP is in the zone and it has the right settings. It's just the visual on the devices page.
I manage to get the Zone to be displayed if I moved the APs to No Zone after which to the correct Zone.

**Comment by simonmorley** [comment]
I believe this only affects boxes that were previously in a zone @AndrewMargarit

**Comment by simonmorley** [comment]
This only affects devices that were using the previous zones. 

Moving to the backend and will run a script to update them all. It's just the metadata that's not generated.
