### ISSUE TITLE
Zones - Table sort

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#204]
![zones- table](https://cloud.githubusercontent.com/assets/2269441/16913039/dee58b14-4cdf-11e6-87a6-0731fefe2d59.gif)
The Boxes Column doesn't have a sorting option
The Network has a sort option however, it does not work.

**Comment by simonmorley** [comment]
Milestones - can you leave with me to add since I'm the only one who's fixing the stuff atm
