### ISSUE TITLE
"filtered" label broken.

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#206]
When searching the devices table, the total of the filtered devices is
 not updated.
(See attachment)

![filtered_label](https://cloud.githubusercontent.com/assets/17065269/16915144/d11f799e-4cfe-11e6-8e99-42dbc4a060fa.gif)

**Comment by simonmorley** [comment]
Is the label broken? Or, is the filtered count broken.

Or both?
