### ISSUE TITLE
Devices - No alert that a box has been reset

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#208]
![reset box](https://cloud.githubusercontent.com/assets/2269441/16921797/e6e7bc12-4d0a-11e6-8e1b-b506b38e3aff.gif)

**Comment by simonmorley** [comment]
I just closed one of these, can you re-open that one please.

**Comment by simonmorley** [comment]
Plus, can you paste the mac of the box in question since I tested last week without issue @AndrewMargarit

**Comment by AndrewMargarit** [comment]
Do you mean this one? https://github.com/cucumber-tony/cucumber-frontend/issues/118

**Comment by AndrewMargarit** [comment]
Or https://github.com/cucumber-tony/cucumber-frontend/issues/185

**Comment by simonmorley** [comment]
#118

**Comment by simonmorley** [comment]
I need the specific device plus the console output when loading the page please.

**Comment by AndrewMargarit** [comment]
They are not the same.
Will simulate and post

**Comment by simonmorley** [comment]
The popup appears every time in development but only on page load. Not if the page is sitting there.

Can you confirm if the popup appears when you load the page. 

If it does not, please paste the console out put.

**Comment by AndrewMargarit** [comment]
The Email has the wrong URL

**Comment by simonmorley** [comment]
This was also causing the zone popup NOT to appear.
