### ISSUE TITLE
Missing <th> in the devices table

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#213]
![missing_th](https://cloud.githubusercontent.com/assets/17065269/16940756/9be2ed24-4d94-11e6-98c2-e39af231f147.jpg)

**Comment by simonmorley** [comment]
@mep253 Can you see if you can fix?

**Comment by mep253** [comment]
Hi @simonmorley, this seems to be fixed already. This issue can be closed.
