### ISSUE TITLE
Transfer device to location not working

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#214]
When trying to transfer a device from one location to another via the "transfer" function in the device settings, it perfectly stays at its location and a success-message prompts.

(my.ctapp.io)

**Comment by simonmorley** [comment]
Strange timing:

https://discuss.cucumberwifi.io/t/transferring-boxes-and-locations/589

We have disabled for the short-term and are implementing a verification system as per thread.

**Comment by simonmorley** [comment]
This is working again. Needs testing
