### ISSUE TITLE
Number of networks in the Zone looks wired

### ISSUE THREAD

**Issue by Illuminatt** [cucumber-tony/cucumber-frontend#219]
After adding some Networks to the Zone the number of Networks looks wired in the Zone-Table - see the screenshot.
![2016-07-20 11_19_20-wi-fi management platform](https://cloud.githubusercontent.com/assets/3488852/16981661/de4e770a-4e6b-11e6-831f-1061c5cc3957.png)
![2016-07-20 11_18_57-wi-fi management platform](https://cloud.githubusercontent.com/assets/3488852/16981662/de4ec50c-4e6b-11e6-8b0d-1bae00b67025.png)

**Comment by simonmorley** [comment]
You beat me to it ;)

**Comment by simonmorley** [comment]
This is probably OK - the front is way ahead of the backend atm. Just waiting for a build to finish which should resolve.

**Comment by simonmorley** [comment]
@Illuminatt You can check in alpha-p and it's fine.

**Comment by Illuminatt** [comment]
Works fine in alpha. Will close the bug after successful retest tomorrow.

**Comment by Illuminatt** [comment]
Retested and ok - closed
