### ISSUE TITLE
Incorrect number of clients and devices

### ISSUE THREAD

**Issue by Illuminatt** [cucumber-tony/cucumber-frontend#222]
_Steps to reproduce:_
1. Add some locations 
2. Connect some clients to locations
3. Delete all locations

_Expected result:_
Number of locations and connected clients should be equal "0"

_Real result;_
Number of Locations is now 73. Maybe with some new build old locations didn't cleared itself from DB.  Every time I add new location the number icnreases. See also screenshots:

![2016-07-21 12_41_37-wi-fi management platform](https://cloud.githubusercontent.com/assets/3488852/17020337/41ae7fe0-4f41-11e6-8416-90b05dc65ecd.png)
![2016-07-21 12_40_50-wi-fi management platform](https://cloud.githubusercontent.com/assets/3488852/17020338/41af2c4c-4f41-11e6-9d2f-344c4e24cf5c.png)

**Comment by Illuminatt** [comment]
AccountID: AA21FC7

**Comment by simonmorley** [comment]
I have 73 also, wondering if it's our version of [42](https://en.wikipedia.org/wiki/42_(number)).

**Comment by simonmorley** [comment]
We didn't delete the clients with the locations. Until now... So, this is actually resolved in the beta brand of the back-end which will hopefully get merged in later this week.

**Comment by simonmorley** [comment]
It's possible you may still have a strange count as some models won't have been deleted. Let us know if it's still happening tomorrow otherwise will close.

**Comment by Illuminatt** [comment]
When I delete newly added location the number is decreasing (for ex. from 80 to 79). Is it possible to reset to "0" the number of locations on the Home Page?

**Comment by simonmorley** [comment]
I will have to do this manually for you. Will discuss account ID in Slack.
