### ISSUE TITLE
Missing - Custom RADIUS/Splash Page Fields

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#223]
The ability to add your own radius details and splash url details is missing in the new interface

screenshot of old dashboard for reference:
![image](https://cloud.githubusercontent.com/assets/7580428/17020786/78ab2ddc-4f3b-11e6-85d9-705edcd09f82.png)

**Comment by simonmorley** [comment]
I think we should move the captive portal settings over to the splash pages. The challenge is that the network includes a load of required data, like the uamsecret. 

I'll start migrating the data over to the splash and put this in later.
