### ISSUE TITLE
Settings - Splash Settings

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#224]
Production CT
Chrome 51.0 and Firefox 47
![settings-splash](https://cloud.githubusercontent.com/assets/2269441/17021657/554a812a-4f41-11e6-89c9-088700c4d912.gif)

**Comment by simonmorley** [comment]
@ZakMooney Can you sort this, that's the ng-show thing remember.

**Comment by AndrewMargarit** [comment]
Also, the Save button doesn't work.
