### ISSUE TITLE
Splash - Disable IOS & Android Popup

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#225]
You can find this option under the "Splash - Edit Splash" and also under the Location Settings - MENU Splash https://github.com/cucumber-tony/cucumber-frontend/issues/224

**Comment by simonmorley** [comment]
@ZakMooney Can you remove from the location settings, the back-end was moved.

**Comment by AndrewMargarit** [comment]
http://docs.cucumberwifi.io/article/125-bypass-ios-and-android-splash-popups
