### ISSUE TITLE
Add validations back to network SSID

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#226]
We remove loads of validations from the network SSIDS so people could add their own unicode chars.

However, the ' breaks the config since it escapes the surrounding ones.

```
option ssid        'Lord of the Fi's'
```

Put the validations back. @AndrewMargarit Can you test if double speak marks are ok in the WiFi config. It would be nicer to allow ' than not.

```
option ssid        "Lord of the Fi's"
```

**Comment by AndrewMargarit** [comment]
That's not going ti fix it. Someone will add " in the SSID.
We need to escape it.
```
option ssid        'Wi-Fi'\''s'
````

'\'

**Comment by simonmorley** [comment]
I'm going to block " instead.

**Comment by simonmorley** [comment]
Actually I've had to escape the whole lot 🎱

**Comment by simonmorley** [comment]
Done in the back-end
