### ISSUE TITLE
Developer - Error messages not showing when creating an App in CT

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#227]
Error 1:
Must be an absolute uri
![apperror](https://cloud.githubusercontent.com/assets/7580428/17028409/6917278a-4f5f-11e6-9c15-42c0bacdd5d1.png)

Error 2:
Must be an https/ssl uri
![apphttperror](https://cloud.githubusercontent.com/assets/7580428/17028468/a4361ee8-4f5f-11e6-95c5-359c121324d5.png)

**Comment by simonmorley** [comment]
Fixed on API side
