### ISSUE TITLE
(layout&design) last opened location gets named in menu on dashboard

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#237]
When you return from a location to the ct dashboard, the locations name will stay in the left navigation menu as context also its not related to this menu any more.
Maybe it should get removed or a link added e.g. "last opened"
![menu_last_location](https://cloud.githubusercontent.com/assets/19971953/17138852/7bbbc076-5342-11e6-9a43-618d3e0536e4.PNG)

**Comment by AndrewMargarit** [comment]
Is not only the location name, is the page where you are coming from.

**Comment by simonmorley** [comment]
@AndrewMargarit Pardon me?

**Comment by ZakMooney** [comment]
![1](https://cloud.githubusercontent.com/assets/7580428/17363085/6b3c53f8-5970-11e6-9097-af4e84524d6f.png)
I believe this is what Andrew meant. It seems to retain the name from any page you came from.
