### ISSUE TITLE
Tooltip has invalid JS within

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#240]
On the splash pages list page, when you hover the name, the tooltip displays junk:

<img width="444" alt="screen shot 2016-07-27 at 11 07 20" src="https://cloud.githubusercontent.com/assets/309336/17171864/6365cb54-53ea-11e6-9ee0-f730830a3e02.png">

**Comment by ZakMooney** [comment]
Unable to replicate.
Tooltip correctly displays time in production and alpha dashboard.

Are you still able to replicate?

**Comment by simonmorley** [comment]
No it's fixed, not sure how.
