### ISSUE TITLE
Devices - Box - Edit

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#248]
Allow custom DNS on WAN when DHCP is set.
![wan](https://cloud.githubusercontent.com/assets/2269441/17288535/89df8e3c-57cd-11e6-98a9-1ae4ef5757b2.gif)

**Comment by simonmorley** [comment]
@AndrewMargarit Don't we also need to change this in the configs?

**Comment by AndrewMargarit** [comment]
Yes, we do.

**Comment by simonmorley** [comment]
@AndrewMargarit Can we move this to the backend so we can add the logic for the configs there.

**Comment by AndrewMargarit** [comment]
Done.

**Comment by simonmorley** [comment]
Ok, will close and track there.
