### ISSUE TITLE
Box description max lengt

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#249]
If the Description of the AP is longer than 23 characters, it will be shrieked and replaced with "..."
![description](https://cloud.githubusercontent.com/assets/2269441/17292842/50ab6a16-57e4-11e6-8d64-545d51c86931.gif)

**Comment by simonmorley** [comment]
Yes. The field is truncated to fix

**Comment by AndrewMargarit** [comment]
It's not Zoom or screen resolution related.

**Comment by simonmorley** [comment]
The field is truncated by a default rule to fit it it exceeds a certain length. I don't see why this is a bug?

**Comment by AndrewMargarit** [comment]
I get why it shrinks on the table view, but it should not on the Device info view.
Even 23 characters is a small value on the table view. 

They should be able to see at least 30-35 characters.

**Comment by simonmorley** [comment]
It's not about what they should or should not be able to see. It's about the spacing on the rest of the page.

**Comment by AndrewMargarit** [comment]
I'm reopening this one.
@ZakMooney @iamzakr can you do something about it?
