### ISSUE TITLE
Privacy Policy - floating free within smaller windows + scrolling

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#255]
this little grey text started getting around while scrolling in a small screen resolution  

![disclaimer](https://cloud.githubusercontent.com/assets/19971953/17330092/be0e4f56-58c5-11e6-923f-eeef45e284a2.PNG)

**Comment by AndrewMargarit** [comment]
Trying to simulate but I can't.

Was it https://alpha-preview.ctapp.io or the production frontend?
What was the screen resolution and browser?

**Comment by Illuminatt** [comment]
Retested on https://dashboard-preview.ctapp.io/#/ and also on https://alpha-preview.ctapp.io 
![privacy policy](https://cloud.githubusercontent.com/assets/3488852/17357542/85d79a0a-595d-11e6-8c1a-5dd9f373c139.gif)

13 inch display
Resolution 1366x768

**Comment by ChristianWinkler** [comment]
its only happening with google chrome (i mean not on firefox)

**Comment by AndrewMargarit** [comment]
Found it.

Is just in Chrome, on resolution bellow 1440 with 16:10 16:9.
It will probably get to the bottom of our list. Not a real critical issue.

**Comment by simonmorley** [comment]
I have this too.

**Comment by simonmorley** [comment]
@ariandora I though we'd discussed this a while back?

**Comment by ariandora** [comment]
@simonmorley we did, you didn't like the 'footer' solution, so I reverted it, tbh I cannot think of another, you ca revert -  9cb229e and check it out again (last time I only send you an img)
