### ISSUE TITLE
String 'Back to Location' on device page is wrong

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#263]
**Actual Behavior**:
 -  on top of the device page a link with the label 'Back to Locations' is shown

** Expected behavior**:`
 - clicking on the link forwards to the devices page
 - The string should be named 'Back to Devices'.

**Additional Information**:
 -  All Browsers

![image](https://cloud.githubusercontent.com/assets/14114203/17408811/f4ae5bb6-5a6c-11e6-8000-5968cfe94366.png)

**Comment by simonmorley** [comment]
@ZakMooney one for you

**Comment by simonmorley** [comment]
If we change this. We need to reconsider whether we're on the devices page or the location page actually.

**Comment by ZakMooney** [comment]
Yeah, I think the confusion here is that there isn't really a "location" page.
The "location" page is actually the devices page.

I think it does make more sense to call it Back to Devices
