### ISSUE TITLE
It's possible to create more than one splash page per network

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#264]
There are two ways how to set up a network with an active splash screen in ct cloud.

->The first way leads to create a new network with a captive-portal. Doing this will create a new splash screen which is assigned but is called "no name" (can be configured later)

->The second way is more tricky, you build a splash screen first with a sophisticated  configuration which needs to be assigned to an already existing or recently created ssid. Working this way, you will have to use the splash screens - network option which is bit hidden and has no check how many Splashscreens are already assigned to this one and only SSID.
> so i managed to get two splashscreens active for one ssid. in fact only one became active but there is no warning or correct display in ct cloud
![network_option](https://cloud.githubusercontent.com/assets/19971953/17434228/840983a2-5b09-11e6-985a-b3e3189c50ca.PNG)
![splash_screens](https://cloud.githubusercontent.com/assets/19971953/17434040/752b43d0-5b08-11e6-9517-60923e5a0ae8.PNG)
![splash_works](https://cloud.githubusercontent.com/assets/19971953/17434045/775dfe72-5b08-11e6-9bd2-35d1e4310872.PNG)

**Comment by simonmorley** [comment]
What do you mean 'safe for work?'

**Comment by ChristianWinkler** [comment]
should just say that this "rule" is not stable with the described way to break it.

**Comment by simonmorley** [comment]
Can we be clear what you're actually expecting here, I don't understand.

**Comment by ChristianWinkler** [comment]
for my understanding each network/ssid or even a zone can not  have more than 1 splash screen/captive page. this works for way 1 but on way 2 there are no limitations

**Comment by simonmorley** [comment]
Ok, got it. I will check the validation...

**Comment by simonmorley** [comment]
We're not going to fix this since we're shortly introducing multiple splash pages per SSID / network.
