### ISSUE TITLE
Weird Grey Button Registration Form

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#265]
<img width="502" alt="screen_shot_2016-08-05_at_13_08_44" src="https://cloud.githubusercontent.com/assets/309336/17436276/d73fad90-5b0d-11e6-9356-76d2dec4e4f6.png">

**Comment by ChristianWinkler** [comment]
i will be there if all fields have valid data but "why" is a good question. The "Advanced  ^" is there on all fields but with no use right now

**Comment by AndrewMargarit** [comment]
@ZakMooney
