### ISSUE TITLE
Add SSID and Radio instead of interface name.

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#270]
On the device page we have a graph showing average SNR, Signal, Noise or Quality.

See screenshot...

![image](https://cloud.githubusercontent.com/assets/14114203/17513927/2d967e88-5e30-11e6-911e-4d29e299400d.png)

**Actual Behavior**:
-  The names of the virtual access points are wlan0, wlan1, wlan0-1, wlan0-2 etc.; these come from the interface names of OpenWrt.
-  The expected behavior is to have the SSID names and the radio frequency instead.

**Additional Information**:
- The shown interface names do not match with the configuration the customer did
- We need the SSID name and the radio, because the same SSID name can be broadcasted by both radios of an AP.
- Proposal is to use the term <SSID name> (<Radio>GHz), e.g. Guest WiFi (2.4GHz)

**Comment by simonmorley** [comment]
Resolved in a forthcoming release.
