### ISSUE TITLE
upper right navigation menu does not close when browsing to locations

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#271]
the upper right navigationmenu stays open when heading to "locations" menu, but the same menu will close when going anywhere else.

**Comment by AndrewMargarit** [comment]
Can you check if this can be replicated in https://alpha-preview.ctapp.io/#/ and https://app.ctapp.io/#/

If so, can you please create a gif or a video of this?
Also which browser,what version and what OS?

**Comment by ChristianWinkler** [comment]
i'm on with win 7 x64 and latest Chrome v51.
i tried it now with 3 frontend versions and found  3 differend behaviours...^^
also the page you come from might be important.... 

On https://app.ctapp.io/#/
![app ctapp io](https://cloud.githubusercontent.com/assets/19971953/17548582/cabb8da4-5eec-11e6-9c1d-8d06a0384a60.gif)

On https://alpha-preview.ctapp.io/#/ 
![alphapreview](https://cloud.githubusercontent.com/assets/19971953/17548681/3268433e-5eed-11e6-85e6-cf9486609fb9.gif)
