### ISSUE TITLE
Clients: "Type" is not in line with the others

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#273]
Tested on Chrome 52 and Firefox 48 on (ubuntu 16.04)

![526b6fbbbaa8953ce900bad727db39031ee527ef](https://cloud.githubusercontent.com/assets/2269441/17547022/c8a88608-5edc-11e6-86b8-568f99b80e04.png)

**Comment by ZakMooney** [comment]
Can replicate on my machine, however it looks to be resolved in alpha-preview
![image](https://cloud.githubusercontent.com/assets/7580428/17898922/6ca23690-6951-11e6-98d0-e0e2c4da377e.png)
