### ISSUE TITLE
Policies - WiFi whitelist not showing as disabled when switching from whitelist enabled option

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#275]
(win 7 x64 / google chrome v51 / all frontends)

When adding a policie/filter for "wifi" it is not possible to switch to "whitelist" if "blacklist" is selected.
I don't think its forbidden because a wifi whitelist can be created if "whitelist" is selected first on "firewall" option. 

![whitelist](https://cloud.githubusercontent.com/assets/19971953/17556787/f6597200-5f14-11e6-859f-75d0c56a2bb0.gif)

**Comment by ZakMooney** [comment]
This is intended.
You cannot whitelist on the WiFi level, only blacklist.

**Comment by ChristianWinkler** [comment]
ok then this should not be possible even when selecting firewall-whitelist first and switch to WiFi.....

**Comment by ZakMooney** [comment]
It actually isn't possible. 
If you try to add a WiFi whitelist you will receive an error message explaining that it is not possible.

Actual issue is slightly different. WiFi whitelist option not showing as disabled when switching from a whitelist enabled option.

**Comment by simonmorley** [comment]
Ok, I will add a check for this. Nice find guys :)

**Comment by ChristianWinkler** [comment]
i can confirm there is an error now: 
"There was a problem processing your request.
     -   Policy can only be block if using this policy type"
for me this ok but its not the smoothest solution - on the day i reported this i had created a wifi whitelist but now i cant reproduce anymore on all frontends.
