### ISSUE TITLE
Devices : Action Required.

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#276]
Except the email and the popup on the AP, here is no other way to alert the user that an action is requered.
![alert](https://cloud.githubusercontent.com/assets/2269441/17562736/0968d0ac-5f24-11e6-839c-c542087a56f1.gif)

**Comment by simonmorley** [comment]
What are you expecting to see??

**Comment by AndrewMargarit** [comment]
The box is not offline. Is expecting an action to be performed by the user.
The AP will be stuck in that state until the user either sees the email or goes to that AP.

I've looked at the events page and could not see an alert in there either.

**Comment by simonmorley** [comment]
We had a tooltip here but disabled it because of this:

https://github.com/cucumber-tony/cucumber-frontend/issues/93

Would that sort it?

**Comment by AndrewMargarit** [comment]
That will do.
We need to put that one later in a centralised place.
