### ISSUE TITLE
voucher validity minutes minimum field input does not match saving requirements

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#279]
When creating new vouchers for a voucher splash you are asked to set timelimit "
Validity Minutes" to at least 5 minutes, but doing this wont let you save and generate vouchers, the pages saving minimum is 60 minutes for this field.

**Comment by simonmorley** [comment]
@ChristianWinkler I cannot replicate this. Can you please provide screenshots of the issue.

**Comment by ChristianWinkler** [comment]
you might as well change just the text for the validity minute field < 60
![animation_voucher](https://cloud.githubusercontent.com/assets/19971953/17801563/334052f6-65eb-11e6-8087-b04bded0552a.gif)

**Comment by simonmorley** [comment]
It wasn't that field causing the problem. The fix in beta should resolve.

**Comment by AndrewMargarit** [comment]
@ChristianWinkler can you confirm it's fixed in beta?
