### ISSUE TITLE
no navigation and save button in firefox for splashscreen designer

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#280]
i have no navigation / save button in splash screen designer app.ctapp.io with firefox 47.0
![firefox_no_buttons](https://cloud.githubusercontent.com/assets/19971953/17620923/20ce633e-6090-11e6-9453-618e8d7ee80e.png)

**Comment by ZakMooney** [comment]
Have been able to replicate this on both of my machines.

It appears there's some something causing the buttons to load under the sidebar initially. Seems related to the "position" style, as toggling this refreshes the buttons and makes them appear above the sidebar.
Changing any other options on the buttons does not make them appear.

![splashdesignbuttons](https://cloud.githubusercontent.com/assets/7580428/17854596/af695b02-686b-11e6-804e-f9c3f5820bb2.gif)

Trying to find out what is causing this

**Comment by simonmorley** [comment]
I dislike the way we've implemented this. Seems ott and messy.
