### ISSUE TITLE
missing restrictions / wrong behavior for special characters for SSID and password

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#283]
right now its possible to create and edit networks and use almost every possible character without any restrictions. Tests showed different effects for using e.g. "&" oder " ' "(apostrophe) as SSID / password.

Expected behavior: following characters should be allowed and supported: 
a-z A-Z 0-9 ! " # $ % & '( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~

Result: buggy characters which to be fixed:
"<>'&

its propably a socketman/openwrt issue, feel free to ask me in slackchat for more input.

**Comment by AndrewMargarit** [comment]
```
"
<
>
'
&
```
Are you saying that SSID's or password that contain these characters don't work?

**Comment by ChristianWinkler** [comment]
>yes<

**Comment by AndrewMargarit** [comment]
```
'
```
Except that one, which is sanitised in the back end, the rest should not cause any issues.

**Comment by ChristianWinkler** [comment]
we tried it yesterday with an ubiquiti lite, its not working as expected. 
<>& get translated to some code
' destroyes the openwrt config
" interrupts ct cloud saver with error

**Comment by simonmorley** [comment]
We used to over validate. Now we added so many international customers, we've dropped off. 

Looks like we have to be more strict again.

**Comment by simonmorley** [comment]
I've checked this and they're all allowed but get santized. 

" becomes:

```
option ssid        'My SSID &quot;'
```

&& becomes:

```
option ssid        'My SSID &amp;&amp;'
```

**Comment by simonmorley** [comment]
Actually, I've just checked the backend and only the " & ' characters are being filtered in this way.

However, the way that they configs are being rendered causes the problem.

The good news though is that the new version of Socketman addresses this. SM will be out later this month so I might close this.

**Comment by ChristianWinkler** [comment]
ok maybe my understanding for "santized" is wrong, what should it mean ? if i enter the password "ernie&bert" in the cloud i will have to enter "ernie&amp;bert" as password to connect... also the radioed displayed ssid for "Peter&Paul" is broadcasted as "Peter&amp;Paul".....

**Comment by simonmorley** [comment]
At the moment, it looks like the configs are being cleaned / sanitized twice.

**Comment by simonmorley** [comment]
I've added a quick fix for now to remove the double sanitize. Changes will be live today

**Comment by ChristianWinkler** [comment]
@simonmorley your fix works for < > and &.
The apostrohe ' is still a problem because it has impact in the openwrt wlan config. Maybe dont allow it in the frontend as easiest fix ?

**Comment by simonmorley** [comment]
Can you paste your openwrt config file with the ' please

**Comment by ChristianWinkler** [comment]
ok i entered e.g. ssid name "_test'ssid_" and in the openwrt wlan config its saved as line
`option ssid        'test\'ssid'` which probably leads to a syntax error.

for the password its "_secret'key_" which is pasted in the configfile as
`option key         'secret'key'` which also leads to a syntax error.

**Comment by simonmorley** [comment]
I'll add a validation to the front and back-end. Don't think the SSID is an issue, it's the passy field that would crash it.

**Comment by simonmorley** [comment]
We've added another validation on the backend for the ' in the password and SSID.  This will be available when the current beta build has been merged in.
