### ISSUE TITLE
Adding a former known device to a location will get the old zone listed even it is in no zone.

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#284]
Adding a former known device to a location will get the old zone listed even it is an no zone.
I know its a repost of an [older issue](https://github.com/cucumber-tony/cucumber-frontend/issues/162)  but i could not find the "reopen" button.

Browser: chrome v51 for win 7 x64 / frontend: app.ctapp.io and other
![animation](https://cloud.githubusercontent.com/assets/19971953/17667809/ccbd89c2-6306-11e6-90cb-827916e0f0d6.gif)

basicly i expect the zone fields to be empty if there isn't any zone assigned during adding process  (manuell/ automatic)

**Comment by AndrewMargarit** [comment]
The AP is not added to a zone.
Looks like a visual on the device list.
@ariandora @gflohr any ideas?

**Comment by simonmorley** [comment]
Fixed on the backend also.
