### ISSUE TITLE
double brackets instead of 1 after adding the first device to a empty zone via no-zone prompt

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#286]
When adding a device to a empty zone via the no-prompt there are double brackets in table instead the number one.
![animation2](https://cloud.githubusercontent.com/assets/19971953/17698887/efaf8db0-63bd-11e6-9f79-f13bfe6b83a1.gif)
of course its temporary but its an eyecatcher

**Comment by AndrewMargarit** [comment]
Can replicate.
Not browser related.
