### ISSUE TITLE
Splash - "More Info" text not displaying on live splash

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#289]
**Actual Behavior**:
 -  `What is the issue?` More info text not displaying on live splash page, only in design
 -  `What is the expected behavior?` More Info should show in the design and on the live page

**Additional Information**:
 -  `Browser Type:` Chrome 
 -  `Browser Version:` Version 51.0.2704.84 (64-bit)
 -  `OS:` Ubuntu 14.04
 -  `Page URL:` Live splash, URL N/A

Design left, Live right
![screenshot from 2016-08-17 12 05 07](https://cloud.githubusercontent.com/assets/7580428/17734325/6ed95944-6473-11e6-8e6d-b8cc742c26e1.png)

**Comment by simonmorley** [comment]
Fixed - missing from splash pages.
