### ISSUE TITLE
(Enhancement) inconsistent use of pagination for tables 

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#290]
in ct we have small tables and big tables, regardless i see pagination only at some of them.
Locations, Triggers, Networks, Zones, Splash, Users have none.
(ok you don't need to add them if entrys are limited to a number which fits on page one)

**Comment by simonmorley** [comment]
Not all the results accept pagination at the moment, that's why. If you put a list of the ones w/o pagination, we will go through the backend.

**Comment by AndrewMargarit** [comment]
@ChristianWinkler

**Comment by iamzakr** [comment]
@ariandora is this resolved?

**Comment by ariandora** [comment]
@iamzakr the code is commented out, the commit is more of a setup for the pagination, as the links information was not always present.

**Comment by simonmorley** [comment]
@iamzakr -> open a ticket internally to ensure all required
controllers have the _links block.

**Comment by iamzakr** [comment]
👍
