### ISSUE TITLE
Audit : Duplicate Email

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#292]
**Actual Behavior**:

Emails are duplicated in the email / audits report.

Emails are still captured when the user doesn't select 'Get Newsletter'

I expect the emails to NOT be duplciated. I expect the emails to NOT appear if they don't choose this.

**Comment by ewansheldon** [comment]
Can no longer see emails being duplicated in audits. Do we know if the captured email issue is continuing or can this be closed?

**Comment by iamzakr** [comment]
Still happening, although less often.
