### ISSUE TITLE
Empty Redirect URL redirects to BBC page

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#294]
**Actual Behavior**:
 -  If the user does not enter a Redirect URL in the Splash Edit Page, then the guest is redirected to a BBC web site
 -  Expected behaviour is, that the guest is redirected to the page he entered before he saw the splash screen.

**Additional Information**:
 -  Tested on Windows 10 with latest Chrome browser

**Comment by simonmorley** [comment]
Obtaining a legitimate URL is unreliable. 99% of the time they user gets sent to Windows update, Apple test or the android pages. 

In order to address this, you'd need to modify the coova source code to try and detect better. 

We may consider a way to set this globally per brand in the future.

**Comment by Molkenbur** [comment]
I guess, Coova Chilli suports this already with this option:

       nouamsuccess
	      Do not return to UAM server on login success, just  redirect  to
	      original URL.

Am I right?

**Comment by simonmorley** [comment]
Yes but it does not work well.

**Comment by AndrewMargarit** [comment]
The original URL in most cases will be either the Microsoft/Android/Apple Captive Portal Detection which as a result in most cases will be confusing for the end user.

**Comment by simonmorley** [comment]
We could change this to redirect to google.com. However, there is a large issue.

In the event the login fails, on some devices, namely Ruckus etc. where we don't have a full integration, we sometimes fall back to a redirection to check if they're logged in.

If we redirect to google, they will send us to a HTTPS page. And the user will see an error.

Whatever we redirect to, it **must** be a non-encrypted page.

**Comment by simonmorley** [comment]
Closing since this appears stale.
