### ISSUE TITLE
Cannot delete a user

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#295]
**Actual Behavior**:
 -  I wanted to delete a user from the Manage Users page. The process looked fine. 
 - But after reloading the page, the user still exists.
 - Now I get an error message while deleting the same user again (see screenshots).
 - Expected behaviour is, that the user disappears after deletion.

![image](https://cloud.githubusercontent.com/assets/14114203/17885776/f10ce3fe-691e-11e6-9efc-1de7f69e7c87.png)

![image](https://cloud.githubusercontent.com/assets/14114203/17885788/01b3f8be-691f-11e6-9f1e-5843a2256fc3.png)

![image](https://cloud.githubusercontent.com/assets/14114203/17885804/12eef412-691f-11e6-8bfa-7d4846b1a28f.png)

**Comment by Molkenbur** [comment]
Reloading the User page make the action menu disappear: 

Users page with action menu:
![image](https://cloud.githubusercontent.com/assets/14114203/17886172/e72fcce6-6920-11e6-9190-9dd52063574a.png)

Users page without action menu:
![image](https://cloud.githubusercontent.com/assets/14114203/17886138/c63dab48-6920-11e6-89d8-1ebcfe00ee65.png)

**Comment by simonmorley** [comment]
This is not where users are deleted.

**Comment by ZakMooney** [comment]
What actions did you take to get to that user page to make it show the action buttons?

**Comment by Molkenbur** [comment]
Just using the menu (see screenshot):
![image](https://cloud.githubusercontent.com/assets/14114203/17902206/ad714b56-6966-11e6-9537-cdeadd751937.png)

**Comment by ZakMooney** [comment]
Unable to replicate your issue with deleting users. I have been able to invite/delete users without issue.

Have been able to replicate the refresh issue.
__________

I can see that your admin roles are showing as N/A. This may be related to your issue.

Are you able to invite/add a new user into that list and then delete them?

**Comment by Molkenbur** [comment]
I tested it again with a new user, I just invited.
Deleting from the GUI gives the same result as before.
Deleting from the API is working fine.

1st the deletion seemed to work fine. But after reloading the page, the user is still in the list.
Now I noticed another detail. The role was changing to N/A after I tried to delete the user.

**Comment by simonmorley** [comment]
This is fixed in the beta build that will be there later.

A user cannot be deleted via this page, the name was wrong. 

It has been changed to 'revoke'
