### ISSUE TITLE
Devices : (Bulk) Payloads Don't Run from Device List

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#3]
Payloads run fine from the individual devices page but not from the location > devices page.

It looks like the request is sent but is missing a parameter for the API.

**Comment by AndrewMargarit** [comment]
![wi-fi management platform 1](https://cloud.githubusercontent.com/assets/2269441/15959801/5a74335c-2ef4-11e6-8c6f-66bf17aa08e5.png)

**Comment by simonmorley** [comment]
Payloads do actually run. 

There is no option to save the output like there is on the individual payloads page.

Hence, the payloads run but don't output.

**Comment by simonmorley** [comment]
Should be resolved in the next build. 

Selected payloads now save by default with no additional user action.
