### ISSUE TITLE
Navigation : Work-flow suggestions

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#30]
Please see attached image files with annotations

[Screen-shots.zip](https://github.com/cucumber-tony/cucumber-frontend/files/304627/Screen-shots.zip)

**Comment by simonmorley** [comment]
Uploading these so we can track.

![2016-06-08_11-38-55](https://cloud.githubusercontent.com/assets/309336/15893587/98e95eaa-2d78-11e6-88c0-128b24e430d3.png)
![2016-06-08_11-46-56](https://cloud.githubusercontent.com/assets/309336/15893592/98ee815a-2d78-11e6-8e1f-5710ac2c0f6f.png)
![2016-06-08_12-01-01](https://cloud.githubusercontent.com/assets/309336/15893588/98ea23ee-2d78-11e6-9401-d90280da1bf5.png)
![2016-06-08_12-02-28](https://cloud.githubusercontent.com/assets/309336/15893589/98ea8f82-2d78-11e6-9cfb-87a7ca13c375.png)
![2016-06-08_12-05-44](https://cloud.githubusercontent.com/assets/309336/15893590/98eb3b76-2d78-11e6-85bd-684979b35b6c.png)
![2016-06-08_12-08-02](https://cloud.githubusercontent.com/assets/309336/15893591/98ebd8a6-2d78-11e6-8432-ab39550775ae.png)
![2016-06-08_12-11-21](https://cloud.githubusercontent.com/assets/309336/15893593/98fadc98-2d78-11e6-86b2-bc758b4990a5.png)
![2016-06-08_12-16-08](https://cloud.githubusercontent.com/assets/309336/15893594/98fe8d48-2d78-11e6-8634-130c95a7d2d1.png)

**Comment by simonmorley** [comment]
I've added locations to the top menu bar.

**Comment by simonmorley** [comment]
@wifinigel Is the inventory still showing as blank for you?

**Comment by wifinigel** [comment]
The following inventory link is still blank:

https://alpha-preview.ctapp.io/#/me/inventory (link from inventory section of front page)

The following link works fine (in left nav list): 

https://alpha-preview.ctapp.io/#/users/nigel-bowden/inventory

**Comment by wifinigel** [comment]
Locations addition to the top menu bar is great! Saves me having to go back to entry page to navigate through the locations panel on the front page.

**Comment by simonmorley** [comment]
Ok, good news about the location link. 

I'm thinking about adding another sidebar menu. Just need to see about consistency. 

See the issue with the inventory. Will get that resolved now. Might move into separate issue.
