### ISSUE TITLE
rudimental location status column - only one state

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#305]
in the locations table there is a "state" column - as a user i expect to see different states e.g. at least active and archived....  
![states](https://cloud.githubusercontent.com/assets/19971953/18082195/0a450bce-6e9e-11e6-8aec-e91ae0e131e0.JPG)

**Comment by simonmorley** [comment]
Which one of those locations is archived?

**Comment by ChristianWinkler** [comment]
its the test_location

**Comment by simonmorley** [comment]
Also fixed. Changes live in <24hrs.

Re-open *after* if this is an issue again.
