### ISSUE TITLE
Alerts - Device alerts switch not working

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#308]
**Actual Behavior**:
 -  `What is the issue?` 

Under Account > Notifications, the Device Alerts switch does not save it's state after switching and refreshing.
 -  `What is the expected behavior?` 

When changing the switch, saving, and refreshing the page, the switch should retain your choice.

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:` 51.0.2704.84 (64-bit)
 -  `OS:` Ubuntu 14.04
 -  `Page URL:` https://my.ctapp.io/#/users/user-name/alerts

**Comment by simonmorley** [comment]
Fixed on backend, changes live later
