### ISSUE TITLE
clients table search & sort not working properly

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#309]
-  `What is the issue?`
  Sorting on the clients table is not possible - it seems that the page reloads when clicking on a column header but the table stays in the same order and there is no hint if its ascending or descending.
  Also this tables search should be connected with the backend i cant search for entrys which aren't present in the actually displayed table page.
  -  `What is the expected behavior?`
    Assuming i have a location with almost 1000 clients in total and about 140 active ones, i want to find the client i am looking for either by a direct search in the complete backend data or by sorting the complete list according to  a certain attribute.

**Comment by iamzakr** [comment]
Closing in favour of #490 
Client search is something we are discussing internally.
