### ISSUE TITLE
Network tables fitted into one table only (way arround issue #80)

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#310]
**Actual Behaviour**:
-  `What is the issue? *`
  In networks section there is a table which ist separated for the three band variations (2.4, 5.0 and dual radio) but at this time online the dual table displays existing networks (all 3 bands) - so it is not possible to see which ssid is broadcasted in which band. Also its not possible to preselect the desired band in while creating a new ssid (the 3 tables might suggest the plus button adds an ssid which fit to the table band - because there isn’t any band selection in the popup). There is already an open github issue #80 but maybe there is an easier way, see the expected behaviour

![how it looks like](https://cloud.githubusercontent.com/assets/19971953/18131790/6f42b8c2-6f94-11e6-89ef-7d1fe88fa7be.gif)
-  `What is the expected behaviour?`
  The user should get an easy overview over his ssids and the used band. The number of ssids is naturally limited to 16 right now and should fit into one table. A new column to show the selected band would be the easiest approach (see next picture)

![idea](https://cloud.githubusercontent.com/assets/19971953/18131796/7699ef32-6f94-11e6-870d-656dedef9f2b.jpg)

**Comment by simonmorley** [comment]
Dupe.
