### ISSUE TITLE
Network: Subnet Mask & Content Filtering missing

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#312]
![netmask](https://cloud.githubusercontent.com/assets/2269441/18278935/ccdd2f42-744b-11e6-8d87-23d451a0ddb3.gif)
**Actual Behaviour**:
 -  `What is the issue? : The Subnet Mask and Content Filtering drop-down do not display the value selected. *`
 -  `What is the expected behaviour?: The value should be displayed /24 /23 /22 | DNS level`
23 /22?`

**Additional Information**:
 -  `Browser Type: Chrome 53 / Firefox 48  *`
 -  `OS: Ubuntu 16.04*`
 -  `Page URL: locations/LOCATION-NAME/networks/NETWORK-ID *`

**Comment by simonmorley** [comment]
This isn't just the networks, it's all the drop downs.
