### ISSUE TITLE
Needing two login attempts when switching between user accounts or having old cache

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#314]
-  `What is the issue? `
Sometime users may not logout before they try to login in a different account. Switching accounts without logging out (or maybe even having old cache in browser) ends in having two attempts to login again. This is confusing - enter brand, email and password again without a suitable hint.

 -  `What is the expected behavior?`
Login with valid credentials always works on the first attempt, regardless which old user account is in the browser cache (and has not been logged out). If the user has to try it twice before it works nothing is getting better.

**Comment by simonmorley** [comment]
@ariandora Can you handle this?

**Comment by simonmorley** [comment]
I think this was fixed in one of today's commits. Please check and re-open if still happening.

https://github.com/cucumber-tony/cucumber-frontend/pull/362
