### ISSUE TITLE
Settings for Splash and Notifications are not saved / loaded

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#315]
**Actual Behavior**:
 -  `What is the issue? *`
Its not possible to store settings for splash and notifications in a location.
fields and switches marked in the next pictures:
![splash settings](https://cloud.githubusercontent.com/assets/19971953/18380397/6f247044-7677-11e6-833b-8698ce88810a.jpg)
![notification setting](https://cloud.githubusercontent.com/assets/19971953/18380399/70991fba-7677-11e6-8e46-3bb0d1b7628d.png)

 -  `What is the expected behavior?`
All fields/switches saved when hitting the save button and all fields are loaded with the latest saved values when the settings page gets opened

**Comment by simonmorley** [comment]
The splash limit has been removed.

Tagged logins was a permissions thing on the backend.

Both fixes are on their way.

Notification settings is an issue with angular material chips. Removing, going back to a text field for simplicity.

**Comment by ChristianWinkler** [comment]
@simonmorley : 
i noticed you made some changes... now the email field supports multiple addressess but they still dont get displayed after reloading / reopening the page. I'm not sure if this is how it was supposed to work. So is there still work in progress ?

**Comment by simonmorley** [comment]
"Push enter to save the email"

Let me know if you still have the problem.

**Comment by ChristianWinkler** [comment]
i checked that the enter key is required.... getting the mail address in a grey frame and clicking on save afterwards the cloud tells me that it got saved. But when i reload or return later the field is empty again.

**Comment by simonmorley** [comment]
Location ID please

**Comment by simonmorley** [comment]
And, are you using the master build of the dashboard?

**Comment by ChristianWinkler** [comment]
ok its working today for me in chrome. 
commit: Build #645e249
but its not working in firefox 48.0.2

i had entered two addresses with chrome but cant see them in firexfox. location ID 1390956538526602171

![image](https://cloud.githubusercontent.com/assets/19971953/18544867/ff16d502-7b36-11e6-9cfb-74cfc4c34fbe.png)

**Comment by simonmorley** [comment]
I would have a look through angular material to see if they have an issue open for the same
