### ISSUE TITLE
Client description toggles between No Name and assigned name over time

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#32]
When looking at the list of clients, noticed that some clients show the name I have maunally assigned them, then a few minutes late the description field shows No Name.

Screen-shots below

![client names issue](https://cloud.githubusercontent.com/assets/19818404/15901308/b1572f72-2d9a-11e6-880d-4ab3355dfdca.png)
![client names issue 2](https://cloud.githubusercontent.com/assets/19818404/15901313/b6fdd124-2d9a-11e6-8489-5c11e9b3ac27.png)

**Comment by simonmorley** [comment]
Going to move your images into this one:

https://github.com/cucumber-tony/cucumber-frontend/issues/14

And keep this over there.
