### ISSUE TITLE
Branding - No error message when selecting brand name/url already in use

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#321]
**Actual Behavior**:
-  `What is the issue?` No error message is displayed when changing your Brand Name or Dashboard URL to one that is already in use. Refreshing page returns Brand Name/URL back to what it was.
-  `What is the expected behaviour?` An error message should show informing you that the Brand Name/Dashboard URL you entered is already in use.

**Additional Information**:
-  `Browser Type:` Chrome
-  `Browser Version:` Version 51.0.2704.84 (64-bit)
-  `OS:` Ubuntu 14.04
-  `Page URL:` https://my.ctapp.io/#/users/zak%20test-71a089ca29/branding

**Comment by simonmorley** [comment]
@ZakMooney  Fixed backend, should be live later today / tomorrow.
