### ISSUE TITLE
iOS 10 Websockets Blocked - Blank Page

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#326]
**Actual Behavior**:
All browsers on iOS 10 display a blank page. The application doesn't load and a blank page is displayed.

See these related issues:

http://stackoverflow.com/questions/39547791/firebase-ios-10-network-activity-indicator-keeps-spinning

**Additional Information**:
 -  `Browser Type:  mobile chrome, mobile safari. Probably others`
 -  `Browser Version:  all`
 -  `OS: iOS 10 only`

----

**Comment by simonmorley** [comment]
The problem lies within webcomponents, which is required by Google charts and graphs.

https://github.com/vaadin/gwt-polymer-elements/issues/133
https://github.com/webcomponents/webcomponentsjs/issues/617

**Comment by WTober** [comment]
Is there any planning when a new version of webcomponentsjs (iOS10fixes) can be used in polymer?

**Comment by simonmorley** [comment]
@WTober I think you're in the wrong repo.
