### ISSUE TITLE
Can't confirm a box has been reset

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#332]
**Actual Behavior**:
 -  `When a box has been manually reset, a confirmation appears. Clicking on this confirmation should reset the ap. In some cases, this throws a 404 error and the client is redirected to the 404 page *`
 -  `The device should be reset to new`

**Additional Information**:
 -  `Browser Type: ALL`

----

**Comment by Oceanspeed** [comment]
Still an issue. 
> AP was having an issue and was manually flashed with the firmware. I've checked out the [Doctor script](http://192.168.65.26/doctor/) and it seems to be communicating fine with CT.

Still unable to reset, resynch unit.
[diagnostic(1).gz](https://github.com/cucumber-tony/cucumber-frontend/files/498022/diagnostic.1.gz)

**Comment by simonmorley** [comment]
The changes have only just gone live. 

This isn't a place to for support. And it's certainly not the place to continue support conversations. 

If you need support, use the forums or the dashboard support widget. 

Your ticket is still open in the dashboard - please continue this there.
