### ISSUE TITLE
Splash Design - Upload picture mising

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#333]
**Actual Behavior**:
 -  `What is the issue? *` The HEADER and BACKGROUND Image Upload button is missing.

**Additional Information**:
-  Obviousley you should have a upload button.

----
![wi-fi management platform 7](https://cloud.githubusercontent.com/assets/2269441/18912001/047b8a56-8578-11e6-819b-328e06f81f47.png)

**Comment by AndrewMargarit** [comment]
@ZakMooney

**Comment by simonmorley** [comment]
@ariandora Looks like the template has been removed completely...

**Comment by simonmorley** [comment]
Actually, it's there. Not sure why it's not rendering...

**Comment by simonmorley** [comment]
The tag was changed from templateURL to template.... I've sorted.
