### ISSUE TITLE
Incorrect number of devices in the locations table

### ISSUE THREAD

**Issue by ariandora** [cucumber-tony/cucumber-frontend#343]
**Actual Behavior**:
 -  `What is the issue? *`

The number of devices in the locations list table does not match the actual number of devices the location has

 -  `What is the expected behavior?`

The number of devices in the locations list table to match the actual number of devices the location has

**Additional Information**:
 -  `Browser Type: *` all
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *` #/locations

**Comment by simonmorley** [comment]
This has been fixed at the API side, the changes will be live in the next 24 hours.

Re-open after 24 hours if still an issue.
