### ISSUE TITLE
Time interval is in 10 year periods

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#35]
When navigating to a location summary age, the time period scale along the base of the client graph shows 10 year time intervals - see screen-shot below:

![location-summary-years](https://cloud.githubusercontent.com/assets/19818404/15904308/6c39afce-2da8-11e6-8ee7-4c86a1fe4fb0.png)

**Comment by simonmorley** [comment]
I think this only happens when there's no data. However, I've checked and can't replicate.

@wifinigel Could you test if this is still happening to you - I had a look at your location on mine, all was fine.

**Comment by wifinigel** [comment]
I suspect you're right. I've not seen this since I first started using the new GUI. Probably best to close this one.

**Comment by simonmorley** [comment]
This happens when there's a single point - there's a bug in the charting library we use.

**Comment by simonmorley** [comment]
This is a problem with all charts that only have a single point.

**Comment by simonmorley** [comment]
Can't fix still...

**Comment by iamzakr** [comment]
fixed currently on beta
