### ISSUE TITLE
DNS setting always disabled in languages other than English

### ISSUE THREAD

**Issue by ariandora** [cucumber-tony/cucumber-frontend#350]
**Actual Behavior**:
 -  `What is the issue? *`

DNS settings always stay disabled if  the selected language is not Eng

 -  `What is the expected behavior?`

DNS settings should work for other languages as well

**Additional Information**:
 -  `Browser Type: *` all
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *` /locations/some-location/some-network

**Comment by simonmorley** [comment]
Fixed in beta thanks to that commit. @ariandora You can close an issue automatically with the following, to save you a job:

https://help.github.com/articles/closing-issues-via-commit-messages/

Something like fixes #350 should do
