### ISSUE TITLE
Boxes API: Internal Server error while reading boxes with a query

### ISSUE THREAD

**Issue by dbrammertz** [cucumber-tony/cucumber-frontend#351]
Executing a query on the boxes endpoint results in an internal server error:
`curl -X GET -H "Content-Type: application/json" -H "Authorization: bearer xxxx" -H "Cache-Control: no-cache" 'https://api.ctapp.io/api/v1/boxes?q=F4-06-8D-6E-5E-FA'`

```
<!DOCTYPE html>
<html>
  <head>
    <title>500 application error</title>
    <style>
      html {
        background: url(assets/5001.gif) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }

      h1 { text-align: center; }
      h2 { text-align: center; }
      h3 { text-align: center; }

      body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      }

      a { color: black; }

    </style>
  </head>
  <body>
    <div id="container" style="margin: 0 auto; text-align: centre; width: 50%;">
      <h1 style="font-size: 100px">500 Error</h1>
      <h2>Sorry, there's been a problem doing whatever you were trying to do. <br>Back-up. Try again.</h2>
      <h3><a href="http://status.ctapp.io">Visit our status page.</a></h3>
    </div>

    </div>
  </body>
</html>
```

Nevertheless the box can be seen by querying all boxes
`curl -X GET -H "Content-Type: application/json" -H "Authorization: bearer xxxx" -H "Cache-Control: no-cache" 'https://api.ctapp.io/api/v1/boxes`

This bug is browser and OS independed.

**Comment by simonmorley** [comment]
I can replicate and can see the errors in the logs also.

**Comment by simonmorley** [comment]
Indexing issue with some devices. Should be resolved but leaving open for 7 days

**Comment by simonmorley** [comment]
@dbrammertz Have you had any further issues with this?
