### ISSUE TITLE
Splash designer menu options are misaligned in Firefox

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#352]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
-  `What is the issue? *`
-  `What is the expected behavior?`

**Additional Information**:
-  `Browser Type: *` Firefox
  ![misaligned_spalsh_menuoptions](https://cloud.githubusercontent.com/assets/17065269/19235560/1c89345e-8efb-11e6-8c81-cdd8ee207df7.jpg)
-  `Browser Version: *`
-  `OS: *`
-  `Page URL: *`

---

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.
> 
> Add screenshots, gifs, illustrations as required to demonstrate your issue.
> 
> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
@ZakMooney Can you check pls.
