### ISSUE TITLE
(Enhancement) ambiguity of address field when creating new locations (should actually say "street")

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#355]
When creating a new location the user gets asked to enter the locations address. There is a field called location address which should actually be named "Street Address" or similar.
After the location became created the same field entry is actually called "Street Address" and in the locations table the column "Address" should be named that way if it contains that string.

On the other hand a field named "Address" should contain the full string set: "street + house number, postcode + city"
![street address](https://cloud.githubusercontent.com/assets/19971953/19260965/569754f8-8f8e-11e6-8edc-c83bfebc7d02.jpg)

**Comment by simonmorley** [comment]
The location address isn't the location street. It's the location address field, hence the name location address. Short of putting the street and postcode on the create page, I don't see how to achieve this.
