### ISSUE TITLE
device reboot function is not working on devices overview

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#356]
When i select reboot device from devices list (ctapp.io)  it fails. On the device page itself it works.

```
af506b67.vendor.js:6 TypeError: c.reboot is not a function
at v (0a4700d8.app.js:7)
at 0a4700d8.app.js:7
at g (af506b67.vendor.js:6)
at af506b67.vendor.js:6
at o.$eval (af506b67.vendor.js:6)
at o.$digest (af506b67.vendor.js:6)
at af506b67.vendor.js:6
at f (af506b67.vendor.js:5)
at af506b67.vendor.js:5
```

i think the wrong function might be linked there.

**Comment by simonmorley** [comment]
The device overview page?

**Comment by ChristianWinkler** [comment]
lets see, you call it "main devices page" where you have the "devices list"

**Comment by simonmorley** [comment]
Screenshots would have helped. @ariandora Could have a look at this.

**Comment by ChristianWinkler** [comment]
tested it today, thx
