### ISSUE TITLE
(Enhancement) Make part of lan switch is actually an IP setting

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#358]
On ctapp.io i can set up a wireless network to use the AP as DHCP server (coova chilli), use lan for dhcp services or i can disable both switches. 

for a better and easier understandig it would help to move the "make part of lan" switch to the IP settings  because they clearly determine each other [and optionaly remove that repeater switch which actually hides the wds bridge option as described in your documentation http://docs.cucumberwifi.io/article/157-creating-a-wireless-bridge]
![new](https://cloud.githubusercontent.com/assets/19971953/19351159/e9ccf0ac-915a-11e6-9533-52d31e0858fc.jpg)

maybe these switches could be summed up to a radio button saying:
DHCP: (on/ off / use lan) but thats optional for my suggested enhancement

**Comment by simonmorley** [comment]
Closing. Not going to implement.
