### ISSUE TITLE
Clients counted multiple times if connected to different devices

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#363]
**Issue:** 
Whenever a client connects to different boxes in a short period (same mac / same IP and same SSID) the client gets counted multiple times.

**Expected behavior:**
Each unique mac represents one client, no matter if the  wlan connection roamed to another device within the same network / location.

This issue also boost the wireless clients graph on the devices overview page which might become confusing if you know your are in a company with 100 devices max but your chart reaches 130 as peak.

**Comment by simonmorley** [comment]
@ChristianWinkler Do you see the connected count increase or just the uniques?

**Comment by ChristianWinkler** [comment]
i know what you mean, you may have two different values (clients and unique clients) . basically i have a location which shows up to 10 wireless clients:
![image](https://cloud.githubusercontent.com/assets/19971953/19435611/e06ff3ce-946b-11e6-969d-d570bb4eb2af.png)
but in the clients list for the last 30 days there are only 6 (none removed). I would recommend to make the chart show "unique clients" then. See:
![clients](https://cloud.githubusercontent.com/assets/19971953/19435816/0404dd80-946d-11e6-9adb-02dfaf21564b.png)

**Comment by simonmorley** [comment]
Ok, I think it's just the uniques count that's causing the problem.

We're just rewiring the collector and will ensure this gets addressed during the the rewrite.

**Comment by simonmorley** [comment]
We have a fix for this which will be merged in over the next day or so.

The down-side being that you will lose historical counts of unique clients for a few days while the databases catch up.
