### ISSUE TITLE
Timezone does not syncronize with OpenWRT timezone

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#364]
in the device settings a timezone can be selected by the user. I changed it and checked the timezones in /etc/config/system on the devices but i doesn't get synchronized. Also it does not affect the logging times in the charts on the device overview. What is the use of this setting?

![image](https://cloud.githubusercontent.com/assets/19971953/19466793/cdbb988a-950d-11e6-8cc1-19dd4857dca7.png)

**Comment by simonmorley** [comment]
It's not for any of those settings and it doesn't apply to the system file by design yet.

For Q&A - please ask the question on the discussions.
