### ISSUE TITLE
Not every change in network settings triggers  a device resync

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#366]
When turning the "Repeater-mode" switch on or off in the network settings the change will not get synchronized with the device. Its necessary to make an additioanl change for a real synchronisation.
E.g. when you change the SSID and click save a resync it triggered, and its the same saves success message.
![repeater mode](https://cloud.githubusercontent.com/assets/19971953/19516226/62b81330-95fb-11e6-88ef-675cd182b397.JPG)

**Comment by ChristianWinkler** [comment]
its the same for the ssid on and off switch i guess. powerfull switch but slightly used....

**Comment by simonmorley** [comment]
What does slightly used mean ?

**Comment by ChristianWinkler** [comment]
just saying that i never unchecked this switch myself this deep in the network settings. when changing ssids on and off i used the zones configuration provided and remove ssids there....this works :smile:

**Comment by simonmorley** [comment]
Ok, we're adding this hopefully this week. Lots of fields added recently...

**Comment by simonmorley** [comment]
Marking as won't fix, in anticipation of the new SM
