### ISSUE TITLE
Wrong url in e-mails for project users

### ISSUE THREAD

**Issue by dvlemplek** [cucumber-tony/cucumber-frontend#369]
The following e-mails include a link that is not usable for project users (e.g.:  https://cucumberwifi.io/#/boxes?q=F4-06-8D-38-3D-2E):
- [ONLINE]
- [OFFLINE]
- [DEVICE ADDED]
- [CHECKUP]
- [BOX RESET]

The link redirects to "...alerts" which leads to an empty page.

**Comment by dvlemplek** [comment]
Any progress on this?

**Comment by simonmorley** [comment]
This was fixed a while back but the issue wasn't closed automatically.

**Comment by simonmorley** [comment]
Device added still needs updating...
