### ISSUE TITLE
Events list : shows AP as MAC addr rather than AP name

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#37]
In the events list, when APs go up/down, the event msg describes them in terms of their MAC addr rather than their AP name, which probably needs fixing? Screen shot provided below:

![box-mac-addr](https://cloud.githubusercontent.com/assets/19818404/15906064/32edb006-2daf-11e6-8670-6f809919da95.png)

**Comment by simonmorley** [comment]
Ah, we changed this for the main dashboard but forgot to do for the list. 

We're systematically going through and changing all AP mentions from the mac address to the description.

**Comment by simonmorley** [comment]
This is now resolved. Events for boxes from now on will appear with the description and not just the mac address. Changes should be live around 5pm GMT.
