### ISSUE TITLE
Chart subtitle "average" switched to "mean" when selecting "average"

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#370]
the chart on the clients overview page: it says average on default but when the user selects "average data" it says "mean". I think its the same chart but 2 names.
![mean average](https://cloud.githubusercontent.com/assets/19971953/19526088/85bc1f70-9623-11e6-8180-77846886e43c.gif)

**Comment by ChristianWinkler** [comment]
this issue affects most charts in default view and their subtitle when selecting the corresponding view from the options drawer: Average -> Mean

**Comment by simonmorley** [comment]
@ZakMooney One for you

**Comment by ZakMooney** [comment]
changed mean to average: e8eb819
