### ISSUE TITLE
Configuring DHCP option type to any other value than 6 (Specifies list of DNS servers to the client) is not possible

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#371]
**Actual Behavior**:
- The default is 6, 
- empty field is not allowed
- any other value has no impact (as I know)
- it is not clear how to configure the device to act as a DNS relay

It is also not easy to know for unexperienced users to know what this option is good for.

**Comment by simonmorley** [comment]
@AndrewMargarit Handing to you, not sure if this is front or back

**Comment by AndrewMargarit** [comment]
It's both I believe.
I'll look into it and come back.

**Comment by simonmorley** [comment]
@AndrewMargarit did you look at this ??

**Comment by AndrewMargarit** [comment]
By default, we add option 6 to our DHCP configuration block.
```
list 'dhcp_option' '6,xx.xx.xx.xx,xx.xx.xx.xx'
```
If we remove this, the DHCP server will send the IP of the gateway and use the upstream DNS server or the one set up in the network config.
