### ISSUE TITLE
Columns in clients table without content / dont show

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#372]
following issues to this table:

![clients table](https://cloud.githubusercontent.com/assets/19971953/19552717/5bc6bb38-96b1-11e6-9cbb-7ea09fc8d674.png)

**Txbps** & **Rxbps** dont show up in the table. Tx Rate and Rx Rate work, maybe they are remains from [issue 46](https://github.com/cucumber-tony/cucumber-frontend/issues/46)

**Splash Users** column does not show anything even if i use splashscreens to login.

**Comment by simonmorley** [comment]
We don't have the tx and rx for numerous reasons in the table so these can be safely removed. Nice spot.

**Comment by simonmorley** [comment]
https://github.com/cucumber-tony/cucumber-frontend/commit/85aa1150ffb34a47e3b3f5d47985890def9c1993
