### ISSUE TITLE
Wrong expand arrow position in Voucher Details

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#379]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` When expanding a panel of Voucher details the position of the expanding icon doesn't get updated.
 -  `What is the expected behavior?` Expand arrow should be sticked to the bottom of the panel

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *`

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.
![voucher1](https://cloud.githubusercontent.com/assets/17065269/19686570/64f92232-9aca-11e6-9f21-8c75958a45b6.gif)

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
That's how it is throughout and something that's part of the MD spec. If you find the spec says differently, re-open.
