### ISSUE TITLE
Navigation : Bar Suggestion

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#38]
This is a subjective opinion, but I like to use top-level nav buttons for common workflow launch points. It;s also useful to have a summary of minor/major/critical issues. 

I've done a very bad mock-up of a suggested use of the top-bar (see image below). Feel free to completely ignore as appropriate :)

![nav-suggestion](https://cloud.githubusercontent.com/assets/19818404/15907047/6415b742-2db3-11e6-8be5-a1abae8ff02e.png)

**Comment by simonmorley** [comment]
We discussed this internally and decided it wasn't really necessary to have a massive list of boxes.

I'd like to see what people think about this - do we need to put this back? 

Right now we have a list of boxes that are alerting. And a list per location.

The search will (soon) be able to search through the boxes too.

I like the alert icons at the top right.

**Comment by wifinigel** [comment]
Yes, would be interesting see how other people feel about this. For me, the usability of tools I've used before is seeing the initial option I need to start a navigation without having to hunt around too much, and then the minimum number of clicks I can do to get there. Again, it;s maybe just a preference thing :)

I've modified my original idea to change the concept slightly to encompass both trains of thought, by maybe making items top-bar sticky if required. I know if will be probably be a lot of coding, so don't worry too much :)

![nav-suggestion-2](https://cloud.githubusercontent.com/assets/19818404/15922474/ba8b6902-2e1f-11e6-8546-83f469bef17e.png)

**Comment by simonmorley** [comment]
In terms of usability, what would happen when using small screen?

**Comment by wifinigel** [comment]
It wouldn't work on a phone type screen too well.

Would it be possible to detect the device/user-agent type and perhaps tailor the experience? For example, if its obviously a laptop or tablet, then provide the experience shown above, If it's anything else or there is any doubt, show only the sticky icons (no accompanying text) along the top bar.

**Comment by wifinigel** [comment]
Just to provide more context to this discussion, here are a couple of screen-shots: one from an Aruba wireless controller & one from a Cisco wireless controller. They both use a the same generalized approach of the main sections in a nav-var along the top, with relevant tasks down the left side of each page as you moved between major sections. This is what I was thinking about when proposing this. It maybe just gives it a more Enterprise  controller or management type feel and is more familiar to people like myself who work on these devices quite a bit.  I've also put in a screen-shot from the Aerohive cloud management application, which again uses a similar look & feel.

![aruba-wlc-gui](https://cloud.githubusercontent.com/assets/19818404/15989645/8aae986a-3074-11e6-81d2-0422a23d13ee.JPG)

![cisco-wlc-gui](https://cloud.githubusercontent.com/assets/19818404/15989647/8f336a50-3074-11e6-97d6-f8f24edf7019.JPG)

![aerohive-gui](https://cloud.githubusercontent.com/assets/19818404/15989648/932d8f8c-3074-11e6-97ff-6db7a1ad6828.JPG)

**Comment by simonmorley** [comment]
Closing for time being. Will reconsider this later on - ideal to add custom menu links to the top bar.
