### ISSUE TITLE
SSH access allowed from public networks

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#380]
When connected to a WiFi network, I can access the ssh server on the AP. This must be prevented by default. There already are firewall rules in place on the device that are intended to prevent exactly that, but they don't match because the interface name is wrong (it's missing the br- prefix for the bridge).

`Chain INPUT (policy ACCEPT 0 packets, 0 bytes)`
`pkts bytes target     prot opt in     out     source               destination`
`0     0 DROP       tcp  --  lan_60014 *       0.0.0.0/0            10.168.103.1         tcp dpt:22`
`0     0 DROP       tcp  --  lan_60014 *       0.0.0.0/0            10.74.245.1           tcp dpt:22`
`0     0 DROP       tcp  --  lan_60014 *       0.0.0.0/0            172.25.200.242       tcp dpt:22`
`0     0 DROP       tcp  --  lan_10887 *       0.0.0.0/0            10.74.245.1          tcp dpt:22`
`0     0 DROP       tcp  --  lan_10887 *       0.0.0.0/0            10.168.103.1         tcp dpt:22`
`0     0 DROP       tcp  --  lan_10887 *       0.0.0.0/0            172.25.200.242       tcp dpt:22`

**Comment by AndrewMargarit** [comment]
I don't believe that is wrong.
Can you paste in here the firewall.user?

**Comment by mbecks** [comment]
WANIF=`route | awk '/default/ { print $8 }'`
. /lib/functions/network.sh
network_get_ipaddr WANIP wan
network_get_subnet local wan
iptables -I FORWARD 1 -i br-lan_60014 -o $WANIF -j ACCEPT
iptables -I FORWARD 1 -i br-lan_10887 -o $WANIF -j ACCEPT
iptables -A INPUT -i lan_60014 -p tcp --dport 22 -d 10.168.103.1 -j DROP
iptables -A INPUT -i lan_60014 -p tcp --dport 22 -d 10.74.245.1 -j DROP
iptables -A INPUT -i lan_60014 -p tcp --dport 22 -d $WANIP -j DROP
iptables -A INPUT -i lan_10887 -p tcp --dport 22 -d 10.74.245.1 -j DROP
iptables -A INPUT -i lan_10887 -p tcp --dport 22 -d 10.168.103.1 -j DROP
iptables -A INPUT -i lan_10887 -p tcp --dport 22 -d $WANIP -j DROP
iptables -I FORWARD -s 10.168.103.1/24 -p tcp -d $local -j DROP
iptables -I FORWARD -s 10.168.103.1/24 -p udp -d $local -j DROP
iptables -I FORWARD -s 10.168.103.1/24 -p icmp -d $local -j DROP
iptables -I FORWARD -s 10.74.245.1/24 -p icmp -d $local -j DROP

**Comment by AndrewMargarit** [comment]
Ok, give me till tomorrow to look at this when I'll get in the office and I'll update the issue.

**Comment by simonmorley** [comment]
@AndrewMargarit @mbecks Checked this locally today and the rule *is* defo missing the br- prefix. 

I can patch the configs easily today however I've just noticed there's a lot of people using SSH internally. We can't therefore just deploy without allowing an option to edit.

Ideally we just put an section in for the undocumented firewall API but this will take some work. I'm going the therefore propose an option for the short-term in the network settings.

**Comment by simonmorley** [comment]
I've updated the configs for this but only on the next version of SM. Should be out v. soon..

Am putting an option in to disable / enable ssh also.

**Comment by simonmorley** [comment]
This is resolved in SMv4 and won't be applied to v3.
