### ISSUE TITLE
Invalid social splashscreen settings on default

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#381]
Creatiing new social splashscreens on ctapp.io currently leads to an invalid configuration. no changes can be made, no red highlighting or hint texts and the splashpage is not working because there aren't any FB or G+ button clickable.

![image](https://cloud.githubusercontent.com/assets/19971953/19728541/177342e8-9b94-11e6-96ac-9ca846e3a0ba.png)

**Comment by simonmorley** [comment]
@ChristianWinkler  Could you run through the text fields and figure out which one causes the problem.

**Comment by ChristianWinkler** [comment]
no i couldn't figure it out. I cant change anything that will remove the "invalid" textline and activate the save button.

**Comment by ZakMooney** [comment]
Appears to be related to default Facebook settings. Simply unselecting Facebook doesn't work.
Have to switch off "allow checkin" or add a facebook page ID.
Will adjust

**Comment by simonmorley** [comment]
Can you sort?

**Comment by ZakMooney** [comment]
Not sure where the defaults are set, unable to find so far

**Comment by ZakMooney** [comment]
resolved in db
