### ISSUE TITLE
Add to zone when creating a network

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#382]
There is no option to add to zone when creating a network.

That's all.

The modal should include a list of zones.

**Comment by ZakMooney** [comment]
![image](https://cloud.githubusercontent.com/assets/7580428/20061373/86b2d51c-a4f7-11e6-80c4-8a417d730b8a.png)

Zone already on new network modal.

Are you referring to some place else? or has this been resolved?

**Comment by simonmorley** [comment]
Oh right.
