### ISSUE TITLE
Box initializing multiple times after registration

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#384]
When registering a box, the box is being initialized multiple times over the course of the first 5 - 10 minutes. The number of initializations seems to vary, but is mostly three in my experience.
I attached a log file that shows the registration process for a device where you can see that the installer was pushed three times with about 2 minutes of normal operation in between.

[log.txt](https://github.com/cucumber-tony/cucumber-frontend/files/555966/log.txt)

It's also interesting to watch the box page during that process, because it switches back and forth multiple times between the "Please connect your device to an Internet connection" screen and the regular device page.

**Comment by simonmorley** [comment]
I saw this today. Not sure what's happening. Might move to the backend though...

**Comment by simonmorley** [comment]
Marking as won't fix in anticipation of the new SM version.
