### ISSUE TITLE
Can't update email settings sliders

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#389]
![cant-change-reg-fields](https://cloud.githubusercontent.com/assets/309336/19850342/f8330624-9f4f-11e6-91d3-6c67db21a208.gif)

**Comment by ZakMooney** [comment]
@simonmorley 
I believe we spoke about not needing Email Capture when using guest access type as guest data already captures email
Or are we sticking with it?

**Comment by simonmorley** [comment]
True but they should either work or be removed. Plus none of the options work. Even when reg is off.

**Comment by ZakMooney** [comment]
Current situation:

Switches disabled when selecting Reg.
If currently on Reg, selecting another access type still has switches disabled after saving, until refreshing the page.
