### ISSUE TITLE
Location map : Satellite view works, Map view shows devices on blank map

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#39]
When accessing the map of a location, boxes on top of a blank map when the 'Map' option is selected.

Satellite view works fine. Blank map shown below

![blank-map](https://cloud.githubusercontent.com/assets/19818404/15922623/a0401600-2e20-11e6-8804-75132b2fc108.JPG)

Satellite map is fine:

![good-map](https://cloud.githubusercontent.com/assets/19818404/15922657/ca850dbc-2e20-11e6-9e18-bd865003e07e.JPG)

**Comment by simonmorley** [comment]
Also, very hard to spot...

**Comment by wifinigel** [comment]
Update: I just realized that the reason the map is blank is the zoom level. If I zoom out, then the road names etc. are shown OK. Apologies, was just a zoom level issue.

Agree with the icons being a bit difficult to see. Maybe a standardized AP icon with a colour indicating its status (red/green) might be better?
