### ISSUE TITLE
Padding on Firmware downloads

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#394]
<img width="845" alt="screen_shot_2016-11-01_at_23_17_15" src="https://cloud.githubusercontent.com/assets/309336/19911177/c0cfe748-a089-11e6-9c04-41f122f2e784.png">

**Comment by ZakMooney** [comment]
Pulled code directly from master, doesn't have that issue.
For some reason it seems to drop that space when it goes live on the servers, but not on my local machine.

**Comment by simonmorley** [comment]
add a ```&nbsp;``` between - grunt strips white space
