### ISSUE TITLE
Deleting users leaves their locations orphaned

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#396]
When deleting a user account, all associated projects are deleted automatically in the process. However, locations that are assigned to these projects are not deleted. This leaves them without a parent project, which means that only the brand admin can access them at this point. (Actually, the original project_id is still referenced by the location, the project just no longer exists.)

The main problem with this behavior is, that any device that is still registered to such a location, can no longer be registered to another location without the intervention of the brand admin, who has to manually remove the device from its old location to make it available again.

Expected behavior would be that when a project is deleted, all associated locations are deleted as well, and the devices registered to those locations are removed automatically.

**Comment by simonmorley** [comment]
Destroying a user will now trigger a deletion of all locations (and aps) they own.
