### ISSUE TITLE
Radius Settings Flex Wrong - Only Half a Page

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#401]
Another one of these - looks like the flex has been changed.

<img width="721" alt="screen shot 2016-11-08 at 18 15 44" src="https://cloud.githubusercontent.com/assets/309336/20111240/859c7ef6-a5df-11e6-817f-6f7f28ecbcc4.png">

Select 802.1.x, scroll down. See problem.

*Another thing, it's NOT clear where these settings are when you select radius. Think we need a message somewhere to say adjust these.*

**Comment by simonmorley** [comment]
@ZakMooney Moonman!

**Comment by ZakMooney** [comment]
![image](https://cloud.githubusercontent.com/assets/7580428/20213157/0c530ea8-a7ff-11e6-9ded-28a51b78627a.png)
Can't seem to replicate. Spacing seems perfectly fine on both devices I've checked.

**Comment by simonmorley** [comment]
@ZakMooney Can you make it as wide as the page then. Right now the host and secret are toooo short.
