### ISSUE TITLE
Turning off content filtering leaves the last dns filter settings set as active

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#402]
when trying to deactivate a content filtering option for an ssid the last dns stays active. This DNS will be used as custom dns and the content filtering is still enabled until the defaults are entered manually.
Expected behavior: default google dns settings should be entered to those fields in order do disable content filtering. Its good to see which DNS IP is actually in use but off should mean off.

**Comment by AndrewMargarit** [comment]
Are you referring to this?
![wi-fi management platform 7](https://cloud.githubusercontent.com/assets/2269441/20137293/7d6f73ae-a671-11e6-8992-e1a5536a9903.png)

**Comment by ChristianWinkler** [comment]
yes, i think its confusing when you select off but you have to enter a dns ip yourself

**Comment by simonmorley** [comment]
It would be better to change the default DNS servers to Google. Or disable content filtering by default and allow the user to enable it.

**Comment by ChristianWinkler** [comment]
yes and yes.

**Comment by simonmorley** [comment]
In fact, the default IS supposed to be 8.8.8.8 and seems to have been changed in the front end at some point.

**Comment by simonmorley** [comment]
It'll default to 'Off' now and the vals will be set to the Google ones. 

However, if you change them / update the values, it won't change them back at any point. That's the EUs decision.
