### ISSUE TITLE
Switch for powered by settings should work for splashscreen & welcomepage

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#403]
there is a switch to turn off the "powered by" option for a splashscreen. If it says "disabled" the powered by polkaspots link is still visible on the welcome page (after successfull login). Clicking on the link leads to a page which says "incompatible device" (tested on android 6 / ios 10.1.1)

Expected behaviour: the switch set the link on the welcome page too.

![image](https://cloud.githubusercontent.com/assets/19971953/20137266/bce113a0-a679-11e6-8a15-69a5eed8b525.png)

**Comment by simonmorley** [comment]
Nice spot

**Comment by simonmorley** [comment]
This is fixed in the login pages. Changes deployed.

**Comment by SaschaQA** [comment]
Powered by is removed from login pages, but still it is visible at the welcome page
