### ISSUE TITLE
No splash pages found (sometimes) when network count exceeds 5

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#405]
When you five more than 5 networks with splash, plus multiple zones. Sometimes the device fails to find the correct splash configs.

**Comment by simonmorley** [comment]
PS. I have a fix but it's on the backend.

**Comment by simonmorley** [comment]
I've pushed an interim fix for this, will test when the build has deployed. Leaving open since it's not a full solution.

**Comment by AndrewMargarit** [comment]
I can confirm this is now working on the locations I've seen it before.
