### ISSUE TITLE
Missing Device Filter on Clients List

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#407]
You should be able to filter by device on the list of clients.

However, the list of devices has vanished.

![screen_shot_2016-11-10_at_11_57_01](https://cloud.githubusercontent.com/assets/309336/20179232/f3431898-a74c-11e6-918a-e22758b233ef.png)

**Comment by ChristianWinkler** [comment]
i'm not sure but there is an "AP description" filter which enables a column "AP Name". You don't mean this right ?

**Comment by simonmorley** [comment]
No, there's a drop-down missing completely. It allows the user to filter by individual devices.

**Comment by simonmorley** [comment]
Confirmed fixed beta
