### ISSUE TITLE
Too many basic rates are set; this may prevent clients to connect

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#409]
**Actual Behavior**:
 -  After configuring the minimum allowed basic rate to 12Mbps, the configured basic rates on the device are: 12, 18, 24, 36, 48, 54
 -  The expected behavior is to have only 12 Mbps configured as basic rate

**Additional Information**:
All configured basic rates have to be supported by clients to be able to connect to the AP. 
This is a risk, because clients might be configured to support less rates. Configuring more than one basic rate gives us no benefit.

This is not true for the standard rates. Here we need all.

**Comment by simonmorley** [comment]
I think that's wrong. The basic rate is the min basic rate. And you need all the other ones otherwise it doesn't work.

**Comment by AndrewMargarit** [comment]
No, it will remain as a list.
