### ISSUE TITLE
Cant filter guests by location with api

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#412]
**Actual Behavior**:
 -  `What is the issue? *` API call for full guest list returns all guests, but adding location search variable returns no guests
 -  `What is the expected behavior?` adding location search variable should return only guests from that location

**Comment by simonmorley** [comment]
Going to close in favour of this:

https://github.com/cucumber-tony/cucumber-frontend/issues/420

Since they're both related.
