### ISSUE TITLE
Devices - View Device - Payloads : Page is empty

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#42]
![wi-fi management platform](https://cloud.githubusercontent.com/assets/2269441/15959718/fc700ea2-2ef3-11e6-9fa4-e65e8fe8ce1e.png)

**Comment by simonmorley** [comment]
@AndrewMargarit I'm not categorising visuals etc. as bugs so I can prioritise higher priority issues.

**Comment by simonmorley** [comment]
Changes on their way.
