### ISSUE TITLE
Zone management allows too many splashscreens per zone

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#421]
Starting with an empty location:

i can create one network with a splashpage enabled. In order to create more splashscreen networks i need to create zones and assign all networks to a zone, otherwise i will get an error message. If i have a done this, i can continue and create more splashscreen networks without error messages.
Result:  auser can have one splashscreen per zone/ per device but multiple splashscreen networks per ssid. OK

But if i have multiple zones with a splashscreen network  in each of them, i can easily assign all networks with splashpage enabled to only one zone without any error message or warning. NOT OK.

![2016-11-22 16_16_22-](https://cloud.githubusercontent.com/assets/19971953/20529169/923f7a32-b0cf-11e6-866b-d63d170c38f4.png)

Expected behavior: There should be an error message and its not possible to save

**Comment by simonmorley** [comment]
We have an enhancement coming with new SM ;)

**Comment by simonmorley** [comment]
There also seems to be the issue that you the networks count is increased also...

```
1. have a location with at least one zone and a splashscreen active network in this zone
2. try to create a second network in this zone with "splashscreen active" in this zone
network can't be created because there is only one network allowed per zone.
But the number of networks for the selected zone will get increased by 1.
```
