### ISSUE TITLE
Mechanism to detect vendor of client device not good enough

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#423]
**Actual Behavior**:
 -  for only 1/3 of all clients, a vendor is shown
 -  The public available list http://standards-oui.ieee.org/oui.txt has a vendor for each MAC

The information source for finding vendors could be better or the parsing is worse.

**Comment by simonmorley** [comment]
Correct. This gets updated periodically and should be done again soon.
