### ISSUE TITLE
Splashpassword changed mail got send for renamed splash at renamed location without names

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#424]
i had a location with an enabled splashscreen (Password) and set the auto-change password function.
After removing the location i still recieved an email which is almost an empty template:

![email](https://cloud.githubusercontent.com/assets/19971953/20600008/b823c996-b251-11e6-98e9-625a2cd8c226.png)

**Comment by simonmorley** [comment]
@ChristianWinkler Do you have the location ID, splash ID or anything that would help us track this down???

**Comment by ChristianWinkler** [comment]
mhm my mistake, the location could not be deleted due to session data so there is a different reason for this mail with almost no information. I renamed the location and tried to delete it at least once.
Splash Page Id should be 79472316182538, but i am not sure. I will try to reproduce this one more time....
i think changing the names might have caused this lack of information in the email. 

*update issue title*

**Comment by simonmorley** [comment]
#confused

**Comment by simonmorley** [comment]
I'm going to close this if you're not able to replicate. Can you update so we can clean up pls.

**Comment by ChristianWinkler** [comment]
its reproduceable till today. Changing the locations name will lead to an email almost empty.

**Comment by simonmorley** [comment]
What is the location ID??

**Comment by simonmorley** [comment]
Also, when you say 'almost empty' - what do you mean?

**Comment by ChristianWinkler** [comment]
almost empty = no unique information there beside the email template and the passwort information.
one of my retest locations Unique ID
3153808520602676007 in Splash Page Id
40422773149059

**Comment by simonmorley** [comment]
What info do you expect?

**Comment by ChristianWinkler** [comment]
there are two "for" in the text which should refer to the locations name and the ssids or the splashscreens name so that the user will know for which networks the new changed password ist valid. actually the locations name gets set there as text until the location name is changed.

**Comment by simonmorley** [comment]
In the future, please include all this right at the start. It'll save all of us a lot of time.

**Comment by simonmorley** [comment]
Resolved, changes live later.

I was unable the find a 'missing location name' but removed the double for for.
