### ISSUE TITLE
enable networks back again via the network settings page fails

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#425]
on ctapp.io: when i try to renable a network (which is currently not aired) it does not come up imediately and reliable.

![image](https://cloud.githubusercontent.com/assets/19971953/20601159/6602bd6a-b257-11e6-9d00-2fca7708689a.png)

Different changes needed to be made first, i think this is a socketman/backend issue and related to [github issue 366](https://github.com/cucumber-tony/cucumber-frontend/issues/366) and will probably fixed with next socketman too. Just don't lose this switch sync with the next socketman.

**Comment by simonmorley** [comment]
It is the same and yes it's already resolved for v2 SM. So, won't fix.
