### ISSUE TITLE
(Automatic) successful AP update does not create Event

### ISSUE THREAD

**Issue by SaschaQA** [cucumber-tony/cucumber-frontend#430]
![events](https://cloud.githubusercontent.com/assets/24247297/20708622/17c5c592-b631-11e6-95da-c5aec8f63150.jpg)
![version](https://cloud.githubusercontent.com/assets/24247297/20708623/17c634be-b631-11e6-9bfb-0811c8dc2cc3.jpg)

According to the Firmware-Version and the AP Runtime it seems that my device has been updated automatically at Nov/26/2016.

But if I look at the events it is not documented that anything happened during that time.
The last 2 entries were forced by a manual update - even if the update succeeded, it was written that my devices failed to upgrade.

**Comment by simonmorley** [comment]
Please test and re-open if you're still having issues.
