### ISSUE TITLE
Factory reset option when removing device

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#437]
Currently, when a device is removed from a location, it is sometimes reset to factory defaults and sometimes not. I don't know how the decision is made, if a device will be reset or not. But I think it would be great to be given the option upon removing the device to manually choose whether the device shall be reset to factory defaults or not.

**Comment by simonmorley** [comment]
This is on our internal list of features and should be added before Chrimbo.

**Comment by simonmorley** [comment]
This has been added, please read through the docs to see how to control the default action.

http://api-docs.cucumberwifi.io/#!/Boxes/

Changes live today at some point.
