### ISSUE TITLE
Clients Listing - No Horizontal Scroll Bar

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#44]
If the fields in the clients display screen is increased so that the screen width of browser is exceeded, no horizontal scroll bar is provided so that client 'Action'  drop-down on right can be accessed. Screen shot below:

![clients-no-scroll-bar](https://cloud.githubusercontent.com/assets/19818404/15983492/267dff08-2fa1-11e6-922d-bcfc26a987df.JPG)

**Comment by simonmorley** [comment]
Not sure how to fix this atm and maintain consistency.

**Comment by simonmorley** [comment]
Forced a horizontal scroll bar when there's additional content. This is pretty much all I can do right now.

We'd have to take out of the card to do properly...
