### ISSUE TITLE
Usage Statistics don't show correct values for Wireless Clients

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#444]
**Actual Behavior**:
The screenshot shows data from the devolo brand admin user dcc@devolo.com.
The Network Stats on the left show 130 connected clients. The red graph in the Usage Statistics diagram shows the number of Wireless Clients over the last 7 days. 
Since the 16th of december these values are zero.

![image](https://cloud.githubusercontent.com/assets/14114203/21308010/58346e42-c5d8-11e6-90a9-e1d9dd13b7da.png)

**Expected Behavior**:
My expectation is, that the number of wireless clients is always bigger than the number of connected clients.

- Page URL: https://my.ctapp.io/#/
- Brand: dcc-nwmgmt

**Comment by simonmorley** [comment]
Resolved on API
