### ISSUE TITLE
SNR values in clients table are wrong for 5 GHz clients

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#448]
**Actual Behavior**:
 - The SNR value of all clients connected to the 5 GHz radio are shown with a too high value (e.g. 103dB instead of 50dB).
 - The shown value is the correct noise value multiplied by (-1).
 - We checked the API and it returns a signal value of 0.
 - An example: The noise value -103dB,
 - the SNR value will be calculated as signal/noise, which is in 0dB - (-103dB).
 - In this example the shown SNR value is 103dB.
 - We checked the signal value on in the SSH console of the box and it is shown correctly as -53dB (iw or iwinfo commands).
 - This happens on an Ubiquiti AP with Cucumber firmware, too.

**Expected Behavior**:
 - If the signal value is e.g. -53dB and the noise value is -103dB, then the correct SNR value should be 50dB.

**Comment by simonmorley** [comment]
@iamzakr Did you resolve this - I think a recent commit closes it.

**Comment by iamzakr** [comment]
😮
👍

**Comment by Molkenbur** [comment]
Hi iamzakr,  I cannot see, that the problem is fixed.
Is there something, I missed? Where did you fix the problem? Do I need SocketMan 4.0 to get it fixed? 

![image](https://cloud.githubusercontent.com/assets/14114203/23123355/4ecaf5ee-f768-11e6-9197-381ee99b26d7.png)

**Comment by iamzakr** [comment]
I checked through a bunch of locations and didn't see the issue anywhere, let me have another look.

**Comment by iamzakr** [comment]
You'll have to excuse my oversight, it's definitely not a consistent issue, I just got lucky (or unlucky) with my test sample and found many 5Ghz clients correctly displaying the SNR. But it does seem to still be an issue, working on it.

**Comment by Molkenbur** [comment]
Thanks for the quick answer. It might be firmware related. To be sure, that the problem does not only occur with our devices, we tested it with Ubiquity and Cucumber firmware, too.

**Comment by iamzakr** [comment]
@Molkenbur I need to check whats in the database, but that client is showing 0dB signal and 103dB noise which would make the calculation correct at the least. Also I could be wrong but I think you can have noise with no signal, so I'm wondering if there is a chance that this is actually correct.

Side note: The graph displaying this data is wrong however. That will be fixed.

**Comment by Molkenbur** [comment]
Hi @iamzakr, you are right. My issue description should mention that, too. Even if 0dB is not the same as zero output power, a signal of 0dB is not likely while stations are connected.
To be honest, I haven't seen a problem with the graph so far.

**Comment by simonmorley** [comment]
This is being moved to won't fix in anticipation of SMv2 moving to beta.
