### ISSUE TITLE
Profile duplicate links on mobile sidebar

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#452]
**Actual Behavior**:
 -  `What is the issue? *` Profile link duplicates in mobile sidebar every additional page load. Duplicates are cleared on browser refresh.
 -  `What is the expected behavior?` Should only be one profile link in mobile sidebar at all times.

[ignore missing "user" label. Fix has been pushed since gif]

![profileprofileprofile](https://cloud.githubusercontent.com/assets/7580428/21424075/47c358b8-c838-11e6-8430-d12c39691f53.gif)

**Comment by simonmorley** [comment]
Fixed in beta
