### ISSUE TITLE
Unable to delete SSIDs when disabled

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#456]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` When an SSID is disabled, any attempt to delete it will result in an error
 -  `What is the expected behavior?` SSID should be able to be deleted regardless of its admin status

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` Version 55.0.2883.87 m
 -  `OS: *`Windows 10
 -  `Page URL: *` https://my.ctapp.io/#/locations/home-lyndhurst-grove-jpiqs9iuj_ptuwohpovuda/networks

![image](https://cloud.githubusercontent.com/assets/19818404/21520885/dc4e58e6-ccef-11e6-86ad-f8f6be18f8c0.png)

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
@wifinigel Nice spot. I've just updated the validation for this on the backend. Changes will be there later today ;)
