### ISSUE TITLE
Status Widget Shows Loading

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#459]
statuspage.io is now returning a 400 error when loading the status.

The curl works ok:

```
curl https://lrlkfrhrjrpk.statuspage.io/api/v2/summary.json
```

Must be something within Angular that's causing the problems

<img width="467" alt="screen shot 2017-01-02 at 16 10 54" src="https://cloud.githubusercontent.com/assets/309336/21592532/1e55e0dc-d106-11e6-9b2a-a62b9d722851.png">

**Comment by iamzakr** [comment]
I can see the error and can replicate it.
Error: 
```
XMLHttpRequest cannot load https://lrlkfrhrjrpk.statuspage.io/api/v2/summary.json. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by iamzakr** [comment]
Fixed with this pull https://github.com/cucumber-tony/cucumber-frontend/pull/473
