### ISSUE TITLE
Security certificate expired

### ISSUE THREAD

**Issue by iamzakr** [cucumber-tony/cucumber-frontend#461]
**Actual Behavior**:
Upon loading the dashboard via the specific dashboard URL (eg. zak-r-dashboard.ctapp.io/ ) an error is raised informing that the security certificate expired on 14th December 2016.
 -  `What is the issue? *`
The security certificate has expired.
 -  `What is the expected behavior?`
No error raised and a valid security certificate in place

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Version 55.0.2883.95 (64-bit)
 -  `OS: *`
Mac OS 10.12
 -  `Page URL: *`
https://zak-r-dashboard.ctapp.io/
any direct dashboard link will raise the error as far as I know.

![screen shot 2017-01-04 at 13 03 25](https://cloud.githubusercontent.com/assets/11335229/21643215/0e8a227e-d27f-11e6-86f8-1354b000892f.png)

**Comment by AndrewMargarit** [comment]
A

**Comment by simonmorley** [comment]
COMMENT
