### ISSUE TITLE
Unprocessable request on login

### ISSUE THREAD

**Issue by iamzakr** [cucumber-tony/cucumber-frontend#466]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *`
When logging in to the dashboard a GET request is made to https://api.ctapp.io/api/v1/brands/my?type=showcase which seems to always return 422

On some logins, an OPTIONS request is made to the same URL which returns 200.

 -  `What is the expected behavior?`
When logging in this GET request should not be made as far as I know

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Version 55.0.2883.95 (64-bit)
 -  `OS: *`
Mac OS 10.12
 -  `Page URL: *`
When logging in from https://id.ctapp.io/login

![screen shot 2017-01-06 at 12 09 13](https://cloud.githubusercontent.com/assets/11335229/21717469/045783f6-d409-11e6-9cc3-4b393bc6c89b.png)
![screen shot 2017-01-06 at 12 09 22](https://cloud.githubusercontent.com/assets/11335229/21717470/0460e69e-d409-11e6-9057-8c6162e3fa62.png)

**Comment by simonmorley** [comment]
One's an OPTION request, the other's a GET.

The OPTION will always be a 200.

@iamzakr - make sure both dashboard && my are added to the filter. And check this doesn't happen with dashboard.ctapp.io

Both these 'brands' can be ignored.
