### ISSUE TITLE
Brands link is missing

### ISSUE THREAD

**Issue by ekesseler** [cucumber-tony/cucumber-frontend#478]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` The brands link is missing when clicking on the tile-menu. When you call https://my.ctapp.io/#/brands the menu is back, but it's missing again after logout/login.
 -  `What is the expected behavior?` The brands link should show.

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Ubuntu 16.04
 -  `Page URL: *` https://my.ctapp.io/#

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by ekesseler** [comment]
![brands-missing](https://cloud.githubusercontent.com/assets/11627677/21926062/79920610-d980-11e6-9620-d5bc9d7c4429.png)

**Comment by ewansheldon** [comment]
Thanks for pointing this out. Will be resolved on our next release this week.
