### ISSUE TITLE
Sorting columns for results with mulitple pages sorts the pages results not the entire results

### ISSUE THREAD

**Issue by iamzakr** [cucumber-tony/cucumber-frontend#490]
![screen_shot_2017-01-16_at_13_25_54](https://cloud.githubusercontent.com/assets/11335229/21985312/e1d43c70-dbf1-11e6-9e65-d44ab48fe00a.png)
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *`
When you use one of the columns to order the results on Locations such as the 'Devices' column it will order the page however it will not order all the results.

> For example if I had:

Page 1

Location | Devices
---------|----------
Location 1 | 3
Location 2 | 2

Page 2

Location | Devices
---------|----------
Location 3 | 1
Location 4 | 6

> and then whilst on the first page sorted by number of devices (ascending) you would see 

Page 1

Location | Devices
---------|----------
Location 2 | 2
Location 1 | 3

> whereas you expect to see

Page 1

Location | Devices
---------|----------
Location 3 | 1
Location 2 | 2

This occurs for all the columns

https://my.ctapp.io/#/locations

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by iamzakr** [comment]
https://github.com/cucumber-tony/cucumber-frontend/issues/309

**Comment by simonmorley** [comment]
Should be resolved by recent commits, some of which are in beta. @iamzakr re-open if still causing issue
