### ISSUE TITLE
Brand triggers schedule not editable

### ISSUE THREAD

**Issue by ekesseler** [cucumber-tony/cucumber-frontend#494]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue?`
Brand triggers schedule not editable. If I enter 00:00 / 00:00 into the hours they won't be saved. If I use 00:01 / 23:59 it will save 02:00 / 00:59.No error is displayed.
 -  `What is the expected behavior?`
Brand trigger should be editable

**Additional Information**:
 -  `Browser Type:` Chromium
 -  `Browser Version:` 55.0.2883.87
 -  `OS:` Ubuntu 16.04 (64-bit)
 -  `Page URL:` https://my.ctapp.io/#/brands/58779265e5b482000dd54a88/triggers/587c8253b2f6b0000d3169cc

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by ewansheldon** [comment]
We have made some changes to the triggers, which should have fixed this issue now. We are unable to replicate the time issue, so could you please try to change the time of your scheduled triggers and let us know if the issue continues.

**Comment by ekesseler** [comment]
[trigger-bug.mp4.zip](https://github.com/cucumber-tony/cucumber-frontend/files/715893/trigger-bug.mp4.zip)

**Comment by ekesseler** [comment]
You will need VLC Player to open the video, sorry for that.
