### ISSUE TITLE
MCS can't be fractional.

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#513]
MCS can only be
- a positive real number.
- Zero
- No value

Under the client's page, go to a client and you will see MCS values of 6.70.

@ariandora Is this similar to your client count issue?

**Comment by ariandora** [comment]
will take a look, should be the same

**Comment by ariandora** [comment]
for the axis value I used:
options.vAxis = {
          format: '0',
          minValue: 4
        };
that might have to be added in the mcsCharts function in the charts. directives;
atm my mcs index is always 0 so I can't really test it, maybe someone else can try it out?
