### ISSUE TITLE
Navigation : Enhancement Request - Breadcumb trails

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#52]
A number of times when using the new interface, I've looked for visual clues about which screen/page I'm in.

It would be nice to see a breadcrumb trail near the top of the current panel to indicate the current location in the GUI. These could also be useful to navigate back to previous pages.

**Comment by simonmorley** [comment]
Which pages are you getting lost on most.

**Comment by wifinigel** [comment]
It's mainly the pages that are accessed from the front page 'Inventory' panel. Once you drop in to that inventory area, there are no visual cues about where you are. Examples below:

![image](https://cloud.githubusercontent.com/assets/19818404/16004027/7aa4a66a-3157-11e6-8e87-aa217e6b701f.png)

The section above is obviously Notification Settings, but there doesn't appear to be any way of determining which overall area of the GUI structure you are in.

The screen-shot below is in the same overall area of the GUI, but again it's not clear where we are:

![image](https://cloud.githubusercontent.com/assets/19818404/16004148/fcbc3b22-3157-11e6-81bb-a18e40eb1587.png)

This whole section feels like an "Admin" area of the management GUI, even though it is accessed from the Inventory panel on the front page. A breadcrumb trail along the lines of : "Home > Admin > Integrations" might clarify where we are (assuming there was an Admin option from the top-bar drop-down menu).

Also, on the screen below, I have opened a location that has no devices yet. Just from looking at the screen , it is not clear where I am:

![image](https://cloud.githubusercontent.com/assets/19818404/16004249/84ed0986-3158-11e6-8085-ba90927a2ca1.png)

Finally, when the side panel is collapsed in a location, there is no obvious visual indication of where you are:

![image](https://cloud.githubusercontent.com/assets/19818404/16004287/ba464872-3158-11e6-9446-02e5c5be073f.png)

**Comment by wifinigel** [comment]
....or it could just be that I am a very stupid user...which is actually quite likely ;-)

**Comment by simonmorley** [comment]
hahha. I see what's happening. That's your profile section but it doesn't say profile. If you click the face at the top > account ---> you get to the same place.

Maybe the inventory doesn't need to be a link or could be removed. However, that's quite an important aspect for those using the per-billing-plans.

The rest is a nav thing. You've hidden the sidebar nav and it stays hidden until you click the burger bar (top left).

Let me see if we can put something in the top bar etc.

**Comment by wifinigel** [comment]
Ah...I see!!! I think I got confused with the initial link through from the front page.

It makes perfect sense now that I know that it's an account section. Yeah maybe something near the top to remind old farts like me where they are might be useful :)

**Comment by simonmorley** [comment]
Have a look what we've done today. You'll find each section now has a name.

We have also added a small menu bar to the LSH of the home page / dashboard to facilitate easier nav and keep a consistent flow throughout.

<img width="547" alt="screen shot 2016-06-14 at 19 26 45" src="https://cloud.githubusercontent.com/assets/309336/16054703/348055de-3266-11e6-8c8d-d9fc36cc058b.png">
<img width="493" alt="screen shot 2016-06-14 at 19 27 02" src="https://cloud.githubusercontent.com/assets/309336/16054705/34818512-3266-11e6-9b3a-87170922af72.png">
<img width="482" alt="screen shot 2016-06-14 at 19 27 08" src="https://cloud.githubusercontent.com/assets/309336/16054706/3482af3c-3266-11e6-9ab9-c070f006ca39.png">
<img width="545" alt="screen shot 2016-06-14 at 19 28 09" src="https://cloud.githubusercontent.com/assets/309336/16054704/34819016-3266-11e6-8a39-334380eb272b.png">

**Comment by wifinigel** [comment]
I like what you've done a lot. Very nice indeed! :)

**Comment by simonmorley** [comment]
Aces 👍

**Comment by simonmorley** [comment]
If you're happier with this, we're going to close :)
