### ISSUE TITLE
Email variables (e.g. Owner, Observer) should be available on brand triggers

### ISSUE THREAD

**Issue by ekesseler** [cucumber-tony/cucumber-frontend#531]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? /webhook/device/added?ap_mac={{ Ap_Mac }} setup as POST leads to...`
 -  `What is the expected behavior? ... a GET /webhook/device/added?ap_mac={{ 206 4ms with the ap_mac variable not beeing resolved. Other variables from the list are also not working, maybe the examples are wrong?`

**Additional Information**:
 -  `Browser Type: Safari`
 -  `Browser Version: Version 10.0.2 (12602.3.12.0.1)`
 -  `OS: macOs Sierra`
 -  `Page URL: https://my.ctapp.io/#/brands/58779265e5b482000dd54a88/triggers/5891b6fd77f0c8000d37b824`

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by ekesseler** [comment]
The setup of the type GET/POST also doesn't seem to work. When you create a webhook as GET, it is set to POST when you edit it.

**Comment by simonmorley** [comment]
The latter seems to be a visual. Updated and still see that it's set to POST. 

Have updated this on beta.

I don't really understand exactly what the other problem is. Are you saying the Ap_Mac variable isn't working. I've tested w/o issue this side.

**Comment by ekesseler** [comment]
I'll post info onto slack.

**Comment by simonmorley** [comment]
It would seem this only affects brand triggers, not the location triggers.

**Comment by simonmorley** [comment]
This should be resolved now. The message should include the dynamic vars again.

Also resolve is the brand tags. Seemingly these were only working for location triggers also.

Please re-open if you continue to have issues.

**Comment by ekesseler** [comment]
location_name={{Location_Name}} doesn't work, also the following values are not loaded in the email channel: Owner, Admin, Editor, Supporter, Observer

**Comment by ekesseler** [comment]
@iamzakr Any news?

**Comment by iamzakr** [comment]
Unfortunately not yet 😓

**Comment by ekesseler** [comment]
Ok, no problem. Can you let me know, when something changed?

**Comment by iamzakr** [comment]
Sure thing

**Comment by simonmorley** [comment]
@ewansheldon can you check this is working now. Toni changed the names of the fields.

**Comment by ekesseler** [comment]
@simonmorley was your comment for this bug?
@iamzakr Do you have any news?

**Comment by ewansheldon** [comment]
@ekesseler we're looking into this as a part of this week's sprint. will let you know when we have an update

**Comment by ewansheldon** [comment]
hi @ekesseler - definitely seems to be a problem with the 'email tags' variables at brand level, so the five you've named above (Owner, Admin, Editor, Supporter, Observer). we're looking into this now.

however i haven't been able to recreate this error with Location_Name for example - sends the variable to webhooks just fine with the box added trigger for me. is it still not working for you?

**Comment by ewansheldon** [comment]
I had a look through these issues yesterday.

So part of the issue is that you were testing the five email variables (Owner, Admin, Editor, Supporter, Observer) inside the body of the email. These five variables are only available as the To Address for email triggers, not in the body or subject of emails and not in webhooks. This is indicated by the fact that they are "Email tags" as indicated by the dynamic variables tooltip (seen in screenshot).

However, we do not currently support these email variables in the brand triggers - only location. We have added a task going forward to set up this functionality. I will remove the email tags from the tooltip now to make that clearer.

Furthermore I haven't had any other issues with variables in webhooks, like Location_Name - if you have a chance to test these please let me know if there is still an issue.

I'm going to rename this issue now to update. I hope this clears things up!

**Comment by ekesseler** [comment]
@ewansheldon I will do a re-test on 10.04.

**Comment by ekesseler** [comment]
location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&short_url={{Short_URL}} works
location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&short_url={{Short_URL}}&created_at={{Created_At}} doesn't work

**Comment by ekesseler** [comment]
@ewansheldon Anything new?

**Comment by ewansheldon** [comment]
apologies @ekesseler - we have raised the issue internally and will try to look at this next week i think - i'll keep you updated

**Comment by ekesseler** [comment]
@ewansheldon @simonmorley any news? just did a restest with trigger 58b3fb7ea7ef7d000d087c19:
...?location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&short_url={{Short_URL}} **works**
...?location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&short_url={{Short_URL}}&created_at={{Created_At}} **doesn't work**

**Comment by ewansheldon** [comment]
morning @ekesseler - this is actually a part of this week's bug sprint, so we're going to take a look while ironing out some other trigger issues.

we should be able to give you an update this week. sorry it's taken a little while

**Comment by ekesseler** [comment]
also not fired:
- id: 591c0c94c8d0b5000f8dd1d2
- channel: webhook
- event: device offline
- method: POST
- url: ...?description={{Description}}&location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&last_heartbeat={{Last_Heartbeat}}&short_url={{Short_URL}}

**Comment by ekesseler** [comment]
These variables don't get resolved in the body of brand triggers (e.g. online / offline)
ids: 591e987614ee1d000f073d1e, 591e9adec8d0b5000f2d8b51

Owner: {{Owner}}
Admin: {{Admin}}
Editor: {{Editor}}
Supporter: {{Supporter}}
Observer: {{Observer}}
Username: {{Username}}

**Comment by ewansheldon** [comment]
morning @ekesseler - see above on owner, admin, editor, supporter and observer. these are only available as email address fields by design, though we have already noted previously adding these as body variables for a feature in the future.

i'll note down the issue with the username for @simonmorley to look at while he is investigating trigger issues.

**Comment by ekesseler** [comment]
@ewansheldon Ok, I set the {{Owner}} Var into the email-to-field (id: 58c64be20390a9000f075e15), but no emails is received

**Comment by ewansheldon** [comment]
is this on a brand trigger?

**Comment by ekesseler** [comment]
Yes

**Comment by ewansheldon** [comment]
please see my message on this thread from the 5th April:

> However, we do not currently support these email variables in the brand triggers - only location. We have added a task going forward to set up this functionality. I will remove the email tags from the tooltip now to make that clearer.

**Comment by ewansheldon** [comment]
also the updated title of this whole github issue!

**Comment by ekesseler** [comment]
@ewansheldon But to have the Username Variable in the Email Body or Webhook URL should be supported?

**Comment by ewansheldon** [comment]
from what i understand, yep. so i've listed it as a bug.

though on the trigger variable tooltips, i can't see it listed (though it is included in the given example) - i'll speak with simon about it

**Comment by simonmorley** [comment]
I can confirm the variables {{ Owner }} etc all work as email recipients for LOCATION triggers. However, by design, they will NOT work for brands.

The {{ Username }} field has now been added to locations, networks, devices, zones & vouchers triggers. I've tested this w/o issue and confirm this variable works fine.

Please note, the {{ Username }} field is the username of the user performing the action.

Please re-open should you have other questions.

**Comment by simonmorley** [comment]
@ekesseler What kind of trigger is this?

**Comment by ekesseler** [comment]
It's an email trigger for the device online event, but the same is true for the offline event / web hook with the same data:

Username: {{Username}}
Description: {{Description}}
Location_Name: {{Location_Name}}
Ap_Mac: {{Ap_Mac}}
Last_Heartbeat: {{Last_Heartbeat}}
Short_URL: {{Short_URL}}

...?description={{Description}}&location_name={{Location_Name}}&ap_mac={{Ap_Mac}}&last_heartbeat={{Last_Heartbeat}}&short_url={{Short_URL}}&username={{Username}}

**Comment by simonmorley** [comment]
device.online / device.offline triggers are system events and are not triggered by a specific user.

The username field relates to the user who performed the event. For example, if a user updates a box, you will see the username in there.

**Comment by ekesseler** [comment]
Ok, wanted to use this as replacement for the online / offline notification email and do a web hook call to my backend so I can send an email to the user.

Is there any way to get to the username via the API and Ap_Mac or the Location?

**Comment by simonmorley** [comment]
You have the resource_id and ap_mac so you should be able to use the API to fetch the box. From there you should be able to fetch the location.

Does that work?

**Comment by ekesseler** [comment]
The user_id is the id of the brand admin, seems he has no permission to access the projects, so I cannot receive the data of the user that added the box?

**Comment by simonmorley** [comment]
You can search for the mac or use the slug. Then you should be able to find the location. Then you should be able to get the location's users?

**Comment by ekesseler** [comment]
I do:

- https://api.ctapp.io/api/v1/boxes?q=F4-06-8D-01-02-03&access_token=...
...
"location_id": 0815,
...

- https://api.ctapp.io/api/v1/locations/0815?access_token=...
...
"user_id": 1234,
...

- https://api.ctapp.io/api/v1/users/1234?access_token=...
...
Super-Brand-Admin
...

As I see it there is only one user in the location, which is the Super-Brand-Admin but I wanted to get the Project-User. Am I doing it wrong?
