### ISSUE TITLE
Navigation : Give the option to display more than 25 Entries per page

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#54]
![wi-fi management platform 2](https://cloud.githubusercontent.com/assets/2269441/16009737/ea10dbd6-3175-11e6-9490-0ee1c42bb8a1.png)

**Comment by simonmorley** [comment]
On what page are you talking about?

**Comment by AndrewMargarit** [comment]
All that contain a table.
So far : 
- Devices
- Clients
- Locations
- Events
- Account - invoices
- Account - History
- Account - Access
- Account - Inventory

**Comment by simonmorley** [comment]
The option used to be there. You're welcome to figure out why it's gone. There was an upgrade to the table recently, I sis of the option was changed.

**Comment by AndrewMargarit** [comment]
Happy days!

**Comment by simonmorley** [comment]
I just added it back to the audit section. Might be able to do a global find replace ;)

**Comment by simonmorley** [comment]
This should be resolved. Have not checked each page though.
