### ISSUE TITLE
Box trigger dont work if device has tags

### ISSUE THREAD

**Issue by SaschaQA** [cucumber-tony/cucumber-frontend#544]
Description:
I tried to send a mail via box.online, box.offline, box.resync trigger.

In all cases this trigger does not run if I have added one or more tags to the device. (No mail is sent and "runs" value does not increase)

If I remove the tags, mails are sent correctly (verified with box.resync).

**Comment by simonmorley** [comment]
Can't replicate, works fine locally and in production.

- Updated box with tags - no trigger.
- Added trigger to box.
- Updated box - trigger sent.

Could you test again and confirm. If it still fails, paste the slug in here and I'll take another look.

**Comment by simonmorley** [comment]
Closing @SaschaQA since we didn't hear back
