### ISSUE TITLE
Standard notification email is send two times

### ISSUE THREAD

**Issue by ekesseler** [cucumber-tony/cucumber-frontend#549]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? The standard notification emails are send two times. One with the project user only as recipient, the other with the brand owner's email as second recipient. E.g.: First mail to: project_user@projectdomain.com ... Second mail to: owner@ownerdomain.com and project_user@projectdomain.com (e.g. ID 8579)`
 -  `What is the expected behavior? There should be two mails with one only to the owner and the other one only to the project user.`

**Additional Information**:
 -  `Browser Type: Safari`
 -  `Browser Version: Version 10.0.2 (12602.3.12.0.1)`
 -  `OS: macOS 10.12.2`
 -  `Page URL: https://my.ctapp.io`

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
@ekesseler Could you plonk the trigger ID in here so I can double check.

**Comment by ekesseler** [comment]
Don't think there is a trigger? These are the standard notification emails, like [BOX ADDED]

**Comment by ekesseler** [comment]
If you want I can forward you one...

**Comment by simonmorley** [comment]
Ah ok. Yeah, got it. Thanks
