### ISSUE TITLE
Front/Home Page Feedback

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#55]
Here are a few items of feedback about the initial GUI front page:

1. The "Usage Statistics" panel always appears to remain at a level of zero. I'm not clear what usage this panel is showing? e.g. Logins, number clients, aggregate throughput..? The vertical scale does not show any units, so I'm not sure what it measures.

2. The "Warnings" panel always seem to show no warnings, but I have had quite a few box up/down events which I might expect to see there?

3. The "Inventory" panel always shows the same number of boxes added this period - is this a billing cycle period? Not sure what this means exactly.

4. I like the Cucumber Status panel - very useful.  Would it be worth maybe adding a traffic light icon to show a red/amber/green status? (See fabulously artistic representation below....)

![image](https://cloud.githubusercontent.com/assets/19818404/16011378/294ce306-317d-11e6-99c5-d0d066827273.png)

**Comment by simonmorley** [comment]
Usage stats is actually the radius sessions. In your case, you have none ;) I think we should add the wireless clients to this instead. I created this to keep track: https://github.com/cucumber-tony/cucumber-frontend/issues/56

Warnings - we're migrating these to a new db since it's timing out under the load.

Inventory - this is for billing only. Still working through this.

Status panel - it does go red / amber if there's a problem! The issue is that there are no problems atm :)

**Comment by wifinigel** [comment]
Thanks for the clarification. :)

How about a immensely reassuring green text "All systems operational" then ;-)

**Comment by simonmorley** [comment]
My colour-blind eyes will think that over! I'm guessing you like colour on the sites you visit!! ;)

**Comment by wifinigel** [comment]
Yes, I guess I do. Always good to see green for status info when there's
nothing to worry about. :)

Most mgt platforms seem to use the convention of "green: good", "orange:
you should start to worry", "red: you're definitely not going to get lunch
today".

**Comment by simonmorley** [comment]
hahaha. We just went for changing the top bar to red. However, when there is an outage or issue, the text is pretty obvious and pulls the full description from here:

http://status.ctapp.io

And also links to that site.

**Comment by wifinigel** [comment]
Looks good - top bar now green :) If ever it goes red....I'll call you :)
