### ISSUE TITLE
Client charts always display 'No graph data'

### ISSUE THREAD

**Issue by ariandora** [cucumber-tony/cucumber-frontend#558]
**Actual Behavior**:
 -  `What is the issue? *`
The charts on both the /client and client/:id pages have no data, despite there being a client connected and streaming a video for a time. The last data I have on my device is from the 9th of Feb.  

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`
 -  `OS: *` MacOs
 -  `Page URL: *`locations/location_id/clients and locations/location_id/clients/client_id

**Comment by simonmorley** [comment]
Not enough information to troubleshoot the issue.
