### ISSUE TITLE
Reports showing data for all Customers if no location created

### ISSUE THREAD

**Issue by SaschaQA** [cucumber-tony/cucumber-frontend#559]
If you did not create any location and then have a look at the reports you will see data for all cucumber usersers.
For example 106.000 individual users, created vouchers, splash access methods and so on.

----
![reportsnolocationct2](https://cloud.githubusercontent.com/assets/24247297/22973013/8fc4dbf4-f37c-11e6-9143-f6b321db9c7c.png)
![reportsnolocationct1](https://cloud.githubusercontent.com/assets/24247297/22972957/44106e94-f37c-11e6-8b3b-cf8587bf99dc.png)

**Comment by simonmorley** [comment]
Thanks for the heads up, all fixed. Changes on way!
