### ISSUE TITLE
DASHBOARD - Chart should show the clients etc. 

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#56]
At the moment, it only shows radius sessions. The chart on the home page should show either radius AND clients. Or it could be customisable.

See here for more info: https://github.com/cucumber-tony/cucumber-frontend/issues/55

**Comment by ewansheldon** [comment]
This looks to be implemented to me - ok to close?

**Comment by ZakMooney** [comment]
Am closing for now.

If it is not implemented, feel free to reopen @simonmorley
