### ISSUE TITLE
Mean device traffic/wifi traffic/wifi usage graph does not make sense

### ISSUE THREAD

**Issue by SaschaQA** [cucumber-tony/cucumber-frontend#573]
If you are looking at a specific device it is possible display the "WiFi traffic" or the "WiFi usage" graph.
These graphs are actually only showing traffic from the Access Point or to the Access Point itself.
I was running iperf tests on the SSID configured on this AP for about 4 hours. the graph did not show any bigger value (always about 0.01Mbps/1 MB).

At last I started an iperf server/client on the AP itself, then I could see some correct values in these graphs.
Actually I don't think it makes sense for the customer to see this value (normally there is only traffic between CT Server and the AP which is about 20MB per day)

![2017-2-3-14-49-16-352](https://cloud.githubusercontent.com/assets/24247297/23205454/351f0b70-f8ea-11e6-8ca8-a70075035911.png)

**Comment by simonmorley** [comment]
The wireless stats are wireless stats, not bandwidth stats. That's why they're called WiFi traffic or usage.

We think there's a reporting issue with some devices at the moment that we're working on.
