### ISSUE TITLE
Devices : Only 2.4 channels are shown under the Channel Column

### ISSUE THREAD

**Issue by AndrewMargarit** [cucumber-tony/cucumber-frontend#575]
For dual radio devices, we need to display both channels under that column.

**Comment by simonmorley** [comment]
Where? Which column?

**Comment by wifinigel** [comment]
Here is a screen shot showing this issue. These APs have the 5GHz channel manually set, but on the 2.4GHz channel is shown:
![image](https://cloud.githubusercontent.com/assets/19818404/23341024/4d1b2410-fc38-11e6-9b40-386edf0c25b4.png)
