### ISSUE TITLE
Scheduled triggers behavior very strange

### ISSUE THREAD

**Issue by iamzakr** [cucumber-tony/cucumber-frontend#579]
Created 2 triggers.
1 should disable my networks daily at 5 AM
1 should enable my networks daily at 6 AM
actually both triggers were running the day before at 5PM, 6PM, 7PM and 8PM
![2017-2-5-12-54-35-373](https://cloud.githubusercontent.com/assets/11335229/23260795/729c00ca-f9cb-11e6-97b7-8ff97b53839c.png)

**Comment by SaschaQA** [comment]
Today (one day later) the trigger startet to run again at 2 PM

**Comment by simonmorley** [comment]
Scheduled triggers are still under heavy development so you should expect changes and for things to break.
