### ISSUE TITLE
Ubiquiti AC Lite AP Only Allows Manual Config of 5GHz Channels 36 - 48

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#581]
It is not possible to manually configure the Ubiquiti AC Lite AP for channels beyond channel 48 from the CT dashboard.  When the channel selection is set to "auto", the the AP may select channels beyond channel 48 itself, but this needs to be available as a manual operation too.

**Actual Behavior**: Not possible to select channels above ch 48 on the 5GHz band
 -  `What is the issue? *` It is not possible to perform manual 5GHz channel planning beyond using channels 36, 40, 44 & 48 which is too limited for general usage
 -  `What is the expected behavior?` Manual configuration of channels 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 140 should also be available for manual selection in the UK

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 56.0.2924.87
 -  `OS: *` Windows
 -  `Page URL: *`https://my.ctapp.io/#/locations/home-lyndhurst-grove-jpiqs9iuj_ptuwohpovuda/devices/5hxipfdwmw8habz7hxpbwq/edit

----

![image](https://cloud.githubusercontent.com/assets/19818404/23341210/f9fab5e0-fc3a-11e6-9cdf-d6ae4bd17c38.png)

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by wifinigel** [comment]
Think this is a duplicate of #252 
https://github.com/cucumber-tony/cucumber-frontend/issues/252

**Comment by simonmorley** [comment]
Closing but still need to address some country specific validations.
