### ISSUE TITLE
Vertical graph/line alignment bad

### ISSUE THREAD

**Issue by SaschaQA** [cucumber-tony/cucumber-frontend#582]
Vertical line should be a little bit mor left to fid the grid line.
Maybe his behavior is caused by english timezone.
Only the graph at device overview is affected by this.
![graph](https://cloud.githubusercontent.com/assets/24247297/23364407/423e108a-fcff-11e6-9b0c-91ed83d2f11b.png)

**Comment by iamzakr** [comment]
Yes, this issue is timezone related. It's open internally, I should've made an issue here also.

**Comment by simonmorley** [comment]
Should be resolved in a forthcoming release.
