### ISSUE TITLE
Audit page side-bar blank when expanded

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#62]
When navigating to the Audit page, if the side-bar is expanded, the side-bar is blank. Screen-shot provided below:

![image](https://cloud.githubusercontent.com/assets/19818404/16056722/bdaf170c-326e-11e6-94ea-48caa3a052d4.png)

**Comment by simonmorley** [comment]
I'm going to close this since we're just testing the usability out with some live data. 

Got a large internal list of things to add to this. Will continue with the other ticket.
