### ISSUE TITLE
Not responsive graphs in Reports

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#626]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` See attachment
 -  `What is the expected behavior?`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *`

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.
![not_responsive_graphs](https://cloud.githubusercontent.com/assets/17065269/24651471/99a50b46-1936-11e7-935c-b9920b6f93ab.gif)

**Comment by ewansheldon** [comment]
Thanks for reporting @mep253 - we're definitely aware of this issue and are currently working on a number of improvements and changes to our charts and reports 😊
