### ISSUE TITLE
Clients list - configurable age-out of clients

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#64]
Currently, clients listed seem to stay in the client table for around 6 months since they were last seen.

Would it be possible to have a configurable age-out so that they drop out after a configurable value (e.g. 4 weeks)? This list could get very large in busy areas?

**Comment by simonmorley** [comment]
Ooh. Likes this.

**Comment by simonmorley** [comment]
Now we only show online clients - you can  change the view to see all
