### ISSUE TITLE
Zones Summary Information - Incorrect information Shown

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#65]
When looking at my zones summary information, the information appears to be incorrect for the 'Downstairs' zone. This zone has no boxes allocated and 2 networks:

![image](https://cloud.githubusercontent.com/assets/19818404/16081571/0386b22a-3306-11e6-9d08-6a9c33827639.png)

If I edit the zone, it shows the correct details:

![image](https://cloud.githubusercontent.com/assets/19818404/16081620/33c96e0a-3306-11e6-9b63-7ef2fbdd653b.png)

**Comment by simonmorley** [comment]
I have a script to run which cleans these up. Will do so later and check back in.

**Comment by simonmorley** [comment]
Had a quick look, this is actually a back-end bug. I'll leave this open here but have opened internally.

This happened to boxes added before a certain date. 

Will update when resolved.

**Comment by simonmorley** [comment]
Should be resolved, we've made a load of changes to zones in the last week.

If still a problem, re-open (when you're not on your holibobs).
