### ISSUE TITLE
Locale doesn't change back from DE to EN

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#657]
@Molkenbur Users are reporting that after changing the locale to DE, they're unable to return to EN.

I've had one user test this today with a private tab and it worked.

Can you kindly get your devs to look into why this is causing issues. Kind of annoying.

**Comment by simonmorley** [comment]
@mbecks @Molkenbur can one of you action this please as we're getting numerous complaints from users about not being able to return to EN.

**Comment by mbecks** [comment]
Did the customers who reported this leave some additional information, e.g. what exactly they did, which browser they were using, etc. ? I am unable to reproduce this with my browser on your production front-end. I can switch back and forth between English and German at will. We also got no such reports for our front-end.

**Comment by simonmorley** [comment]
There's been a few reports mainly Chrome. They all had to clear their cookies and or local cache.

I actually suspect there's something overriding it since I ended up in DE Twitter the other day. We seem to use the same cookie name - which is logical.
