### ISSUE TITLE
Devices dashboard doesn't fully show

### ISSUE THREAD

**Issue by ekesseler** [cucumber-tony/cucumber-frontend#669]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? On a high resolution (1920×1080), the devices dashboard doesn't show fully.`
 -  `What is the expected behavior? The devices dashboard (no devices added yet) should be shown.`

**Additional Information**:
 -  `Browser Type: Safari`
 -  `Browser Version: Version 10.1.1 (12603.2.4)`
 -  `OS: macOS Sierra 10.12.5`
 -  `Page URL: https://my.ctapp.io/#/locations/<slug>`

![screenshot](https://cloud.githubusercontent.com/assets/11627677/26616972/cacc3a50-45d2-11e7-880f-a5bd4d8e1db6.png)

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
Affirmative Jim. Works on Chrome, not on Safari. @ZakMooney Can you look into this please. There's a bug in angular material that causes this - might need to remove the flex attributes, can't remember exactly.

**Comment by ZakMooney** [comment]
https://github.com/cucumber-tony/cucumber-frontend/pull/682
Dashboard now showing fine on Safari
