### ISSUE TITLE
Period selection does not work on client view page

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#694]
**Actual Behavior**:
 -  `What is the issue? *`
On the View page of a specific client, I click on any other time period, but the graphs are not changing. Even, if I press on the update icons. I have to reload the page to see the correct graphs.
 -  `What is the expected behavior?`
Just after pressing any other period, the new graphs with the new period are loaded  

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Newest
 -  `OS: *`
Windows 10
 -  `Page URL: *`
https://my.ctapp.io/#/locations/thomas-home-jhqppijqepiaqnrndoe1gg/clients/40-88-05-E7-D7-A6?period=60m

----

![image](https://user-images.githubusercontent.com/14114203/27234936-26d13c26-52bf-11e7-981c-623cb6343b38.png)

**Comment by ewansheldon** [comment]
closing this as we have now switched to date pickers for more flexibility. feel free to make suggestions or pull requests if you find a better option for the date picker
