### ISSUE TITLE
Pin Open Left Nav Panel?

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#70]
Would it be possible to (optionally) pin open the Nav panel on the left side of each page?

For instance, on the home screen if I open the Nav panel, then click through to Locations, Reports, Audit or Events, the left panel disappears on the page I click through:

![image](https://cloud.githubusercontent.com/assets/19818404/16107673/c349e0d4-3395-11e6-90e7-e6cce725b226.png)

Click on Reports:

![image](https://cloud.githubusercontent.com/assets/19818404/16107687/db2a37b2-3395-11e6-8d8e-c098025a2799.png)

Left panel has gone on new page.

I guess this wouldn't work so well on mobile devices, but when using a laptop, would save a few clicks having to re-expand the left nav panel.

Perhaps it might look something like this? (Apologies again for my 1995 GUI design skills) :

![image](https://cloud.githubusercontent.com/assets/19818404/16107853/ed59631c-3396-11e6-8ab5-015f713ec661.png)

**Comment by simonmorley** [comment]
It's actually controlled by a cookie apart from on the pages that you need full width, like the reports and audits. 

It should stay open on the users and locations pages.

**Comment by wifinigel** [comment]
Yes, that's exactly how it works for me.

To give this some more context, I was thinking of an instance where a re-seller or MSP has a large number of locations/customers and keeps this GUI open all day on a big screen for performing configuration/monitoring. The navigation path will generally start with the Locations, Reports or event link and drill down in to the sub-levels below that. 

To move around the GUI, I personally tend to hit the Home (Cucumber) link and then drill down from there. If the left-hand nav panel was pinned open, it would just be a convenience which would work well on the larger screen.

To be honest, this is probably getting in to the realms of personal preferences and maybe even nit-picking. I wouldn't worry about it. Maybe it is something to try out a later date if anyone else raised it :)

**Comment by simonmorley** [comment]
I can make this happen!

**Comment by simonmorley** [comment]
Implemented now on the audits page, but not the dashboard. Usability is an issue there. It's not right to open by default... 

Working on a way to 'pin' it open. Stay tuned
