### ISSUE TITLE
Device name missing in client table

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#703]
The client overview table has a name column that always shows n/a at the moment, even for clients that actually have a name. Because of #702 it's currently impossible to assign a name to a client, but if you have a client that already had a name assigned to it, this name is not shown in the table. You can see the name on the individual client's details page but it's quite cumbersome to click through every client to find a specific one you named earlier.

**Comment by mbecks** [comment]
Actually, there's a lot of information missing from the clients table right now. Especially when enabling additional columns from the settings menu. Looking at the result from the API call, I can see that some of the values are just 0 or an empty string, while others are completely missing from the result object.

**Comment by ewansheldon** [comment]
could you please make a note of any you notice that are missing in the index call and we can get this sorted as soon as possible? thanks @mbecks

**Comment by mbecks** [comment]
Always zero are:
- SNR
- Signal
- MCS Index
- Expected Tput

Always empty string:
- Device Name (AP Description ?)

Missing from the data model:
- Description (Name)
- Manufacturer
- Splash User
- Policies
- Type

There are also some columns that are configurable but are actually missing from the table:
- Expected Tput
- AP Description (only header missing)
- Splash User (only header missing)
- Type

**Comment by simonmorley** [comment]
Device name is back - the update can take a few seconds for future reference.

Manufacturer, policy and AP description are planned for re-addition later. 

MCS is showing 0 on SocketMan v4 clients but ok with v3.

Closing since we have this open internally.
