### ISSUE TITLE
Period filter on devices detail page doesn't trigger heartbeat chart reload.

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#705]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` Changing the period doesn't affect the heartbeat chart on devices detail. 
Only page reload does.
 -  `What is the expected behavior?`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *`

----
![heartbeat_period](https://user-images.githubusercontent.com/17065269/27382718-c1da4120-5690-11e7-91b7-06570d83bf75.jpg)

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by ewansheldon** [comment]
now fixed in beta - thanks for raising
