### ISSUE TITLE
Device SNR chart shows 2.4 GHz for all radios

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#706]
The recently updated device SNR chart shows the SSID with the radio frequency in parentheses. The frequency is always 2.4 GHz, even for 5 GHz radios. The metrics endpoint returns "freq":"2" for all interfaces.

**Comment by ewansheldon** [comment]
hi @mbecks could you please send the link to an example box for this issue? thanks

**Comment by mbecks** [comment]
https://my.ctapp.io/#/locations/mandarin-singapore-en1jihbgxywoq4oqoerf5g/devices/pi8vi7ivmbpok1b9ohzy-w

**Comment by simonmorley** [comment]
Affects v3 only
