### ISSUE TITLE
Device SNR chart shows SSID null

### ISSUE THREAD

**Issue by mbecks** [cucumber-tony/cucumber-frontend#707]
The device SNR chart sometimes shows SSID null instead of the actual SSID name. Even though I only have two SSIDs (on 2.4 and 5 GHz each), the metrics endpoint returns six interfaces instead of four. Two of them actually have SSID "null". This occurred after I deleted an existing network and created a new one.

**Comment by simonmorley** [comment]
Moving forwards, can you define whether this affects v3 or v4 boxes or both.
