### ISSUE TITLE
Scheduled time settings for triggers are "broken" after save

### ISSUE THREAD

**Issue by mep253** [cucumber-tony/cucumber-frontend#725]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Page URL: *`
![trigger_action_time](https://user-images.githubusercontent.com/17065269/27584978-f3fee758-5b42-11e7-8c28-4897bddaf803.gif)

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
@mep253 Use the format ```fixes #id ``` in your commit messages to automatically close these ;)
