### ISSUE TITLE
Networks - When add new network from networks summary page, default network key used

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#78]
When adding a new network from this page:

![newssid1](https://cloud.githubusercontent.com/assets/19818404/16173073/c981f032-358d-11e6-9b33-0e5f94d16c2b.JPG)

And enter the network password on this pop-up panel:

![newssid2](https://cloud.githubusercontent.com/assets/19818404/16173075/d5794610-358d-11e6-805c-ce6045e671d3.JPG)

When editing the network afterwards in this screen, the the network password is my GUI login password, not the password I used when created the network:

![newssid3](https://cloud.githubusercontent.com/assets/19818404/16173078/f6d457a0-358d-11e6-93e3-d8fc67f613a7.JPG)

Looking at the example above, I used the network password 'FredFred' when creating it, but the password shown is my CT GUI login password.

**Comment by simonmorley** [comment]
Good old auto fill :)

**Comment by wifinigel** [comment]
Oops.... *blush*
Yes, confirmed. 

Would it be worth changing the underlying field name so that it doesn't trigger auto-complete for people who perhaps fall down the same hole as me?

**Comment by simonmorley** [comment]
Yeah we've been working though all the troublesome ones. Either we've missed this or the browser has changed the way it works. 

What version are you using?

**Comment by wifinigel** [comment]
It looks like this is LastPass auto-filling the password field, Goes away if I log out of LastPass.

**Comment by simonmorley** [comment]
@wifinigel Can you see if the changes we just pushed made any difference to this. There are a few tricks to sort this, trying to find the best one...

**Comment by wifinigel** [comment]
Just tried - still have same result. Do I need to log out or clear cookies/history?

**Comment by AndrewMargarit** [comment]
Should not make any difference, but you can certainly try logging out and getting back in.

**Comment by wifinigel** [comment]
Yes, checked this again....LastPass still seems to auto-fill my GUI pwd in this field.

**Comment by simonmorley** [comment]
Can't find a fix, will keep looking. Happens in Chrome intermittently too.
