### ISSUE TITLE
Networks - Summary Information & Filtering

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#80]
Currently, the filtering for the network summary does not appear to work correctly. Here is a summary of my networks:

![image](https://cloud.githubusercontent.com/assets/19818404/16176113/f2d76042-35fc-11e6-8f52-0f8d1024999f.png)

The CuT-psk network is assigned to 5GHz only, but appears even though the '2.4 & 5gHz' filter is selected. Looking at the SSIDs over the air, the SSID is (as expected) only being broadcast on the 5GHz band:

![image](https://cloud.githubusercontent.com/assets/19818404/16176121/3daa51ba-35fd-11e6-828d-972935eca8c5.png)

The filtering of the network listing does not appear to work correctly. If I select 5GHz, I see no networks listed, but would expect to see CuT-psk shown:

![image](https://cloud.githubusercontent.com/assets/19818404/16176127/78e10774-35fd-11e6-9f1f-381aff41c23d.png)

Additionally, I'd like to suggest the following updates:
1. Filter selections to be:
   - All - shows 2.4GHz-only, 5GHz-only & 2.4 & 5Ghz networks
   - 2.4GHz & 5GHz - shows networks enabled on both bands
   - 2.4GHz-only - shows networks enabled on 2.4GHz band only
   - 5GHz-only - shows networks enabled on 5GHz band only
2. In the summary list, the bands used by each SSID to be shown in summary list. For example:

![image](https://cloud.githubusercontent.com/assets/19818404/16176177/e468db88-35fe-11e6-9c6e-fa0e3d204109.png)

**Comment by simonmorley** [comment]
Agreed. That is very misleading.

**Comment by simonmorley** [comment]
@iamzakr @ewansheldon Fixed???

**Comment by iamzakr** [comment]
fixed
