### ISSUE TITLE
Action Drop-Down in FireFox

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#83]
The appearance of the 'Action' drop-down menu looks quite a bit different in Chrome compared to Firefox. Both are being used on a laptop on Windows 10. Looks like text alignment has an issue in Firefox:

Chrome :

![image](https://cloud.githubusercontent.com/assets/19818404/16177739/7bf3d90c-362d-11e6-93b5-66899fcdcd33.png)

Firefox (47.0):

![image](https://cloud.githubusercontent.com/assets/19818404/16177745/9140caa4-362d-11e6-851e-fb55b898b3b5.png)

**Comment by wifinigel** [comment]
Checked on Android too. Same issue in Firefox 46.0.1 on my Android tab (Android 5.0.2 - Samsung SM-T530)

**Comment by simonmorley** [comment]
There's actually a bug in Angular Material:

https://material.angularjs.org/latest/demo/menu

https://github.com/angular/material/pull/8675

Will see if an update helps.

**Comment by simonmorley** [comment]
Not fixed in latest release. Will have to wait for their changes.

**Comment by simonmorley** [comment]
Actually fixed in a slightly older version...

**Comment by simonmorley** [comment]
The older version of Angular Material breaks the styling on the other pages. Will wait for a full fix.

**Comment by mep253** [comment]
Hi everyone,
it is actually a FF-BUG ( https://bugzilla.mozilla.org/show_bug.cgi?id=984869 - display: flex doesn't work for button elements)
For our custom style i've fixed it with
```
md-menu-item > .md-button {
    display: inline;
}
```

**Comment by simonmorley** [comment]
@mep253 I added this but the rule breaks the styling on the other drop downs.

Check for yourself - add the rule and then look at the top RHS menus on any page. Padding all weird.

**Comment by mep253** [comment]
@simonmorley i have the rule all the time, but i didn't noticed anything. Now, when you say that... I also saw, that the other menu links are not vertically aligned in Chrome. Do you mean that?

If so, to restrict the rule only to the button elements helped me:  
```
md-menu-item > button.md-button {
    display: inline;
}
```
