### ISSUE TITLE
Slack Integration - Variable Substitution of Pre-canned Trigger Examples Does Not Appear to Fully Work

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#85]
When creating triggers that alert in to Slack, the pre-canned example does not seem to produce meaningful output.

Here is the out seen in Slack:

![image](https://cloud.githubusercontent.com/assets/19818404/16178359/7acd2320-363d-11e6-997b-bf895ed77796.png)

Here is the default event definition for a network update event:

![image](https://cloud.githubusercontent.com/assets/19818404/16178367/a04d0d68-363d-11e6-853f-ac1ca8a68742.png)

Here is the trigger/event info:

![image](https://cloud.githubusercontent.com/assets/19818404/16178369/b63ab288-363d-11e6-87a6-819a75a15666.png)

**Comment by wifinigel** [comment]
Looking at this, it looks like the correct event variables just need to be used. The pre-canned trigger definitions look like they just need updating. 

This definition worked well for a network config update:

The configuration of the network "{{Ssid}}" was updated at location: {{Location_Name}} (Update made at by {{Username}})

![image](https://cloud.githubusercontent.com/assets/19818404/16180291/4f89f7d8-3679-11e6-8e6a-6356932b8d09.png)

**Comment by simonmorley** [comment]
Can we keep similar issues together, easier to track. Going to close and keep in this one: https://github.com/cucumber-tony/cucumber-frontend/issues/49

Referencing so we don't miss these.
