### ISSUE TITLE
Radio Settings - Beacon Interval Settings

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#87]
Although the beacon interval settings are hidden away under the Advance Radio settings, I think they they should be made even more inaccessible if possible. Adjusting these if you don't understand the implication is very bad. Generally, it is not regarded as good practice to change this at all.

Also, if changes are made to the interval slider, it is very difficult to set back to 100 (I couldn't manage to do it  - 99 was a close as I could get.)

![image](https://cloud.githubusercontent.com/assets/19818404/16178589/a08fd600-3644-11e6-9c9b-8ba3e58441fe.png)

I'm not sure of the best way to implement this, but I think it needs to be looked at.

**Comment by simonmorley** [comment]
Eeek.

**Comment by simonmorley** [comment]
Affirmative Jim, I think we should remove that!!!

**Comment by simonmorley** [comment]
We can allow via an API call for those really brave :)

**Comment by simonmorley** [comment]
Be gone with you naughty beacon interval slider, you are no more.
