### ISSUE TITLE
Enhancement Request: Zones - Device membership

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#88]
I think the zones feature is a very powerful feature which is particularly useful for larger networks (IMHO).

If possible, I would like to see some updates to the methods available to discover members of  a zone and adding members (i.e. boxes) to a zone. 

1. On this zone summary page, would it be possible to make the 'Boxes' number a clickable link that would drop through to a devices listing, which uses the zone name as the search term:

![image](https://cloud.githubusercontent.com/assets/19818404/16206206/2bb1a92c-371f-11e6-84d1-e0197adbfd64.png)

This would allow a easy method of finding all boxes assigned to a zone. (This works great from the search bar within the devices page by the way, which is great...but you're bound to have a few old farts like me that don't realize you can do that)

2. Would it be possible to have the option to change the zone that a device is assigned to from within the 'Edit' page of the device itself? This is currently achieved by selecting the 'Edit Zones' drop-down option, but it would also be useful to be able to do it from within the box configuration itself. This is maybe a personal preference thing...I've just found myself hunting around for it a few times as I expected in to be part of the device configuration - again, this is likely to be 'old fart' territory. Now....what day is it again...?

**Comment by simonmorley** [comment]
Fab, thanks. 

We've taken the edit zone button out for the time being. Mainly because there was three places to add to a zone. 

We consolidated into the list view - the aim was to allow people to bulk add etc.

We've got a revamp to the zones coming soon, including the report filtering :)

**Comment by simonmorley** [comment]
This is more doable now we've updated the way the zones work. Moving to a July milestone.

**Comment by simonmorley** [comment]
Zones now show the correct count of boxes. 

Adds zone name to boxes show page.

References https://github.com/cucumber-tony/cucumber-frontend/commit/4c6b1c9ed24716f773fb95a51f2b4b8f66b662c7

**Comment by simonmorley** [comment]
You can now change the box zone from the box edit page

<img width="638" alt="screen shot 2016-07-14 at 18 11 28" src="https://cloud.githubusercontent.com/assets/309336/16848633/8d6b8be2-49ee-11e6-83e9-379da2481dc2.png">

**Comment by simonmorley** [comment]
Old fart aside, this was a fabulous suggestion!
