### ISSUE TITLE
Vouchers - Searching and deleting vouchers

### ISSUE THREAD

**Issue by ZakMooney** [cucumber-tony/cucumber-frontend#92]
![deletebatch](https://cloud.githubusercontent.com/assets/7580428/16232704/89bfd0e4-37c3-11e6-8c8f-283be9acc193.png)

Problem processing request deleting voucher batch

----------

Two vouchers, same username, one with password and other with date as password
![doubleuserpass](https://cloud.githubusercontent.com/assets/7580428/16232763/bb248f4e-37c3-11e6-93fa-d25d18606dde.png)

----------

Location > Vouchers

Should be able to search for a specific voucher

**Comment by simonmorley** [comment]
@ZakMooney Did you mean disabling batch?

**Comment by simonmorley** [comment]
Delete batch was returning a 422 because the codes had been used. We've now added the correct error message.

**Comment by simonmorley** [comment]
Disabling a batch now disables all associated codes.

**Comment by simonmorley** [comment]
Duplicate vouchers will be removed today
