### ISSUE TITLE
Safari Tooltip Flies in from Top LHS

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#93]
First reported by Mr. Sam. The tooltip zooooms in from the top:

![naughty-safari](https://cloud.githubusercontent.com/assets/309336/16232880/1d57d284-37c4-11e6-8ddb-b9033a2648d8.gif)

See this issue in the angular repo:

https://github.com/angular/material/issues/8818

**Comment by wifinigel** [comment]
See the same thing in Firefox. Hover over SSID field in the Client listing page and see it fly in from top left.

Also seen once or twice in Chrome, but **very** infrequent.

**Comment by dmitryshurshilin** [comment]
I see the same in the latest Chrome pretty often (in 5% of cases).

**Comment by simonmorley** [comment]
This has been updated in the material repo now and the bug I raised closed.

Perhaps someone can have a look.
