### ISSUE TITLE
APs on Map Report Wrong Summary Information

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#94]
When clicking on an AP on a map, the dummary information displayed about that AP appears tp be incorrect. In the example below, the AP shows 0 SSIDs & no zone, which is incorrect. The number of connected clients appears to be correct:

![image](https://cloud.githubusercontent.com/assets/19818404/16236443/5628fe1a-37d0-11e6-83a5-cdefa3a1601f.png)

The second AP below also appears to have the same issue:

![image](https://cloud.githubusercontent.com/assets/19818404/16236480/731aabe0-37d0-11e6-875f-7fecef1419fe.png)

**Comment by simonmorley** [comment]
The zones thing is related to https://github.com/cucumber-tony/cucumber-frontend/issues/65 so I will get that fixed when I do that.

The rest should be ok. Still some visuals to fix but the data is good.
