### ISSUE TITLE
Box Reboot Does Not Create Event

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#96]
When a box is rebooted, no event is created in the event log (and hence no triggers fire). Here is the menu option used to reboot:

![image](https://cloud.githubusercontent.com/assets/19818404/16239044/08a02d7a-37db-11e6-8781-831439cdfc60.png)

Observing the AP being rebooted, the actual reboot does occur as requested, but no corresponding log event is seen.

**Comment by simonmorley** [comment]
Moving to our internal backend section.

**Comment by simonmorley** [comment]
Added this to next build, will be cooked later this evening :)

**Comment by simonmorley** [comment]
If you find another other triggers missing, please let us know.

**Comment by wifinigel** [comment]
Will do - I've been having fun with Slack triggers and seeing what
emoticons etc. I can put in for various triggers.

On 21 June 2016 at 20:41, Simon (Big Chief) Morley <notifications@github.com

**Comment by simonmorley** [comment]
Sorting the trigger formatting is next on the list. Think we have most events covered - open to other suggestions. 

Going to implement the cpu / client alert when we're past the milestone.

**Comment by wifinigel** [comment]
Here are my triggers for Slack so far. Feel free to plunder or ignore as
you see fit :)

Network config update:
:pencil: The configuration of the network *{{Ssid}}* was updated at
location: *{{Location_Name}}* (Update made at by *{{Username}}*)

Box down:
:bell: Box *{{Description}}* in location *{{Location_Name}}* has gone
off-line (last contact was at {{Last_Heartbeat}})

Box Up:
:no_bell: Box *{{Description}}* in location *{{Location_Name}}* has come
back on-line

Box reset:
:boom: Box *{{Description}}* in location *{{Location_Name}}* has been reset
by *{{Username}}*

Box resync:
:left_right_arrow: Box *{{Description}}* in location *{{Location_Name}}*
has been re-synced by *{{Username}}*


On 21 June 2016 at 21:01, Simon (Big Chief) Morley <notifications@github.com

**Comment by wifinigel** [comment]
The box reboot event now creates a log entry, but the description field is
blank so that there is no message field in the event summary:

[image: Inline images 1]


[image: Inline images 2]

On 22 June 2016 at 00:56, Simon (Big Chief) Morley <notifications@github.com

**Comment by simonmorley** [comment]
One of the workers still has to catch up, should be deployed later today.
