### ISSUE TITLE
Slack Triggers - Limit of 6 Triggers But No Notification of Limit

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#98]
There appears to be a limit of 6 triggers that can be added (I'm guessing it's on the free plan).

Once 6 triggers have been added (Slack triggers in my case), when the 7th trigger is added, there is no error message once that trigger is saved to indicate that there is an issue (i.e. a limit has been reached). 

The 7th trigger is not created, but once the save button is clicked, the button becomes greyed out, with no indication that the trigger has not been created, or why.

I think there should ideally be an error message to stop the 7th trigger creation being started, rather than allowing the form being completed at all.

**Comment by simonmorley** [comment]
Can't replicate

<img width="869" alt="screen shot 2016-06-22 at 12 26 08" src="https://cloud.githubusercontent.com/assets/309336/16264943/9174a4f2-3874-11e6-8b78-82116174c35f.png">

**Comment by wifinigel** [comment]
Screen share? I still have the issue....

On 22 June 2016 at 12:26, Simon (Big Chief) Morley <notifications@github.com

**Comment by simonmorley** [comment]
Console log output please :)

**Comment by wifinigel** [comment]
....can't seem to track down the console log option? (I'm used to CLI debug commands, not this new-fangled Web GUI stuff...)

Is this browser logging or something in your GUI ?

**Comment by simonmorley** [comment]
No problem. There's a guide here. 

http://docs.cucumberwifi.io/article/204-chrome-inspector-debug-splash-pages

Make sure you're on the js console and do the save. The outer should appear

**Comment by wifinigel** [comment]
You're too polite....you should have posted

RTFM:
http://docs.cucumberwifi.io/article/204-chrome-inspector-debug-splash-pages

On 22 June 2016 at 14:11, Simon (Big Chief) Morley <notifications@github.com

**Comment by wifinigel** [comment]
Any good?

![image](https://cloud.githubusercontent.com/assets/19818404/16268061/a41a35d0-3884-11e6-955c-e6a91683ccdf.png)
